'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ginfes.com.br/cabecalho_v03.xsd"), _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.ginfes.com.br/cabecalho_v03.xsd", IsNullable:=False)> _
Partial Public Class cabecalhotatui

    Private versaoDadosField As String

    Private versaoField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token")> _
    Public Property versaoDados() As String
        Get
            Return Me.versaoDadosField
        End Get
        Set(ByVal value As String)
            Me.versaoDadosField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")> _
    Public Property versao() As String
        Get
            Return Me.versaoField
        End Get
        Set(ByVal value As String)
            Me.versaoField = Value
        End Set
    End Property
End Class

