'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'

'''<remarks/>

'''<remarks/>

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ginfes.com.br/servico_enviar_lote_rps_resposta_v03.xsd"), _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.ginfes.com.br/servico_enviar_lote_rps_resposta_v03.xsd", IsNullable:=False)> _
Partial Public Class EnviarLoteRpsRespostatatui

    Private itemsField() As Object

    Private itemsElementNameField() As ItemsChoiceTypetatui

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("DataRecebimento", GetType(Date)), _
     System.Xml.Serialization.XmlElementAttribute("NumeroLote", GetType(String), DataType:="nonNegativeInteger"), _
     System.Xml.Serialization.XmlElementAttribute("Protocolo", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("ListaMensagemRetorno", GetType(ListaMensagemRetorno), [Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd"), _
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")> _
    Public Property Items() As Object()
        Get
            Return Me.itemsField
        End Get
        Set(ByVal value As Object())
            Me.itemsField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"), _
     System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property ItemsElementName() As ItemsChoiceTypetatui()
        Get
            Return Me.itemsElementNameField
        End Get
        Set(ByVal value As ItemsChoiceTypetatui())
            Me.itemsElementNameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
 System.SerializableAttribute(), _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/servico_enviar_lote_rps_resposta_v03.xsd", IncludeInSchema:=False)> _
 Public Enum ItemsChoiceTypetatui

    '''<remarks/>
    DataRecebimento

    '''<remarks/>
    NumeroLote

    '''<remarks/>
    Protocolo

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("http://www.ginfes.com.br/tipos_v03.xsd:ListaMensagemRetorno")> _
    ListaMensagemRetorno
End Enum
