'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<System.Data.Linq.Mapping.DatabaseAttribute(Name:="SGEDic_Demo")>  _
Partial Public Class SGEDicDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertEmpresa(instance As Empresa)
    End Sub
  Partial Private Sub UpdateEmpresa(instance As Empresa)
    End Sub
  Partial Private Sub DeleteEmpresa(instance As Empresa)
    End Sub
  Partial Private Sub InsertControle(instance As Controle)
    End Sub
  Partial Private Sub UpdateControle(instance As Controle)
    End Sub
  Partial Private Sub DeleteControle(instance As Controle)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.nfseabrasf.My.MySettings.Default.SGEDic_DemoConnectionString1, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Empresas() As System.Data.Linq.Table(Of Empresa)
		Get
			Return Me.GetTable(Of Empresa)
		End Get
	End Property
	
	Public ReadOnly Property Controles() As System.Data.Linq.Table(Of Controle)
		Get
			Return Me.GetTable(Of Controle)
		End Get
	End Property
End Class

<Table(Name:="dbo.Empresas")>  _
Partial Public Class Empresa
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Codigo As Integer
	
	Private _Nome As String
	
	Private _NomeReduzido As String
	
	Private _StringConexao As String
	
	Private _Inativa As System.Nullable(Of Short)
	
	Private _SQLServer As String
	
	Private _DBOlap As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnCodigoChanging(value As Integer)
    End Sub
    Partial Private Sub OnCodigoChanged()
    End Sub
    Partial Private Sub OnNomeChanging(value As String)
    End Sub
    Partial Private Sub OnNomeChanged()
    End Sub
    Partial Private Sub OnNomeReduzidoChanging(value As String)
    End Sub
    Partial Private Sub OnNomeReduzidoChanged()
    End Sub
    Partial Private Sub OnStringConexaoChanging(value As String)
    End Sub
    Partial Private Sub OnStringConexaoChanged()
    End Sub
    Partial Private Sub OnInativaChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnInativaChanged()
    End Sub
    Partial Private Sub OnSQLServerChanging(value As String)
    End Sub
    Partial Private Sub OnSQLServerChanged()
    End Sub
    Partial Private Sub OnDBOlapChanging(value As String)
    End Sub
    Partial Private Sub OnDBOlapChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Column(Storage:="_Codigo", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property Codigo() As Integer
		Get
			Return Me._Codigo
		End Get
		Set
			If ((Me._Codigo = value)  _
						= false) Then
				Me.OnCodigoChanging(value)
				Me.SendPropertyChanging
				Me._Codigo = value
				Me.SendPropertyChanged("Codigo")
				Me.OnCodigoChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_Nome", DbType:="VarChar(50)")>  _
	Public Property Nome() As String
		Get
			Return Me._Nome
		End Get
		Set
			If (String.Equals(Me._Nome, value) = false) Then
				Me.OnNomeChanging(value)
				Me.SendPropertyChanging
				Me._Nome = value
				Me.SendPropertyChanged("Nome")
				Me.OnNomeChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_NomeReduzido", DbType:="VarChar(20)")>  _
	Public Property NomeReduzido() As String
		Get
			Return Me._NomeReduzido
		End Get
		Set
			If (String.Equals(Me._NomeReduzido, value) = false) Then
				Me.OnNomeReduzidoChanging(value)
				Me.SendPropertyChanging
				Me._NomeReduzido = value
				Me.SendPropertyChanged("NomeReduzido")
				Me.OnNomeReduzidoChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_StringConexao", DbType:="VarChar(255)")>  _
	Public Property StringConexao() As String
		Get
			Return Me._StringConexao
		End Get
		Set
			If (String.Equals(Me._StringConexao, value) = false) Then
				Me.OnStringConexaoChanging(value)
				Me.SendPropertyChanging
				Me._StringConexao = value
				Me.SendPropertyChanged("StringConexao")
				Me.OnStringConexaoChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_Inativa", DbType:="SmallInt")>  _
	Public Property Inativa() As System.Nullable(Of Short)
		Get
			Return Me._Inativa
		End Get
		Set
			If (Me._Inativa.Equals(value) = false) Then
				Me.OnInativaChanging(value)
				Me.SendPropertyChanging
				Me._Inativa = value
				Me.SendPropertyChanged("Inativa")
				Me.OnInativaChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_SQLServer", DbType:="VarChar(50)")>  _
	Public Property SQLServer() As String
		Get
			Return Me._SQLServer
		End Get
		Set
			If (String.Equals(Me._SQLServer, value) = false) Then
				Me.OnSQLServerChanging(value)
				Me.SendPropertyChanging
				Me._SQLServer = value
				Me.SendPropertyChanged("SQLServer")
				Me.OnSQLServerChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_DBOlap", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property DBOlap() As String
		Get
			Return Me._DBOlap
		End Get
		Set
			If (String.Equals(Me._DBOlap, value) = false) Then
				Me.OnDBOlapChanging(value)
				Me.SendPropertyChanging
				Me._DBOlap = value
				Me.SendPropertyChanged("DBOlap")
				Me.OnDBOlapChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Table(Name:="dbo.Controle")>  _
Partial Public Class Controle
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)

	Private _Codigo As Integer

	Private _Descricao As String
	
	Private _Conteudo As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
	Partial Private Sub OnCodigoChanging(value As Integer)
	End Sub
	Partial Private Sub OnCodigoChanged()
    End Sub
    Partial Private Sub OnDescricaoChanging(value As String)
    End Sub
    Partial Private Sub OnDescricaoChanged()
    End Sub
    Partial Private Sub OnConteudoChanging(value As String)
    End Sub
    Partial Private Sub OnConteudoChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub

	<Column(Storage:="_Codigo", DbType:="Int NOT NULL", IsPrimaryKey:=True)>
	Public Property Codigo() As Integer
		Get
			Return Me._Codigo
		End Get
		Set
			If ((Me._Codigo = Value) _
						= False) Then
				Me.OnCodigoChanging(Value)
				Me.SendPropertyChanging()
				Me._Codigo = Value
				Me.SendPropertyChanged("Codigo")
				Me.OnCodigoChanged()
			End If
		End Set
	End Property

	<Column(Storage:="_Descricao", DbType:="VarChar(255) NOT NULL", CanBeNull:=false)>  _
	Public Property Descricao() As String
		Get
			Return Me._Descricao
		End Get
		Set
			If (String.Equals(Me._Descricao, value) = false) Then
				Me.OnDescricaoChanging(value)
				Me.SendPropertyChanging
				Me._Descricao = value
				Me.SendPropertyChanged("Descricao")
				Me.OnDescricaoChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_Conteudo", DbType:="VarChar(255) NOT NULL", CanBeNull:=false)>  _
	Public Property Conteudo() As String
		Get
			Return Me._Conteudo
		End Get
		Set
			If (String.Equals(Me._Conteudo, value) = false) Then
				Me.OnConteudoChanging(value)
				Me.SendPropertyChanging
				Me._Conteudo = value
				Me.SendPropertyChanged("Conteudo")
				Me.OnConteudoChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
