'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute("CompNfse", [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class tcCompNfse
    
    Private nfseField As tcNfse
    
    Private nfseCancelamentoField As tcCancelamentoNfse
    
    Private nfseSubstituicaoField As tcSubstituicaoNfse
    
    '''<remarks/>
    Public Property Nfse() As tcNfse
        Get
            Return Me.nfseField
        End Get
        Set
            Me.nfseField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property NfseCancelamento() As tcCancelamentoNfse
        Get
            Return Me.nfseCancelamentoField
        End Get
        Set
            Me.nfseCancelamentoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property NfseSubstituicao() As tcSubstituicaoNfse
        Get
            Return Me.nfseSubstituicaoField
        End Get
        Set
            Me.nfseSubstituicaoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcNfse
    
    Private infNfseField As tcInfNfse
    
    '''<remarks/>
    Public Property InfNfse() As tcInfNfse
        Get
            Return Me.infNfseField
        End Get
        Set
            Me.infNfseField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcInfNfse
    
    Private numeroField As String
    
    Private codigoVerificacaoField As String
    
    Private dataEmissaoField As Date
    
    Private identificacaoRpsField As tcIdentificacaoRps
    
    Private dataEmissaoRpsField As Date
    
    Private dataEmissaoRpsFieldSpecified As Boolean
    
    Private naturezaOperacaoField As SByte
    
    Private regimeEspecialTributacaoField As SByte
    
    Private regimeEspecialTributacaoFieldSpecified As Boolean
    
    Private optanteSimplesNacionalField As SByte
    
    Private incentivadorCulturalField As SByte
    
    Private competenciaField As Date
    
    Private nfseSubstituidaField As String
    
    Private outrasInformacoesField As String
    
    Private servicoField As tcDadosServico
    
    Private valorCreditoField As Decimal
    
    Private valorCreditoFieldSpecified As Boolean
    
    Private prestadorServicoField As tcDadosPrestador
    
    Private tomadorServicoField As tcDadosTomador
    
    Private intermediarioServicoField As tcIdentificacaoIntermediarioServico
    
    Private orgaoGeradorField As tcIdentificacaoOrgaoGerador
    
    Private construcaoCivilField As tcDadosConstrucaoCivil
    
    Private idField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
    Public Property Numero() As String
        Get
            Return Me.numeroField
        End Get
        Set
            Me.numeroField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CodigoVerificacao() As String
        Get
            Return Me.codigoVerificacaoField
        End Get
        Set
            Me.codigoVerificacaoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property DataEmissao() As Date
        Get
            Return Me.dataEmissaoField
        End Get
        Set
            Me.dataEmissaoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property IdentificacaoRps() As tcIdentificacaoRps
        Get
            Return Me.identificacaoRpsField
        End Get
        Set
            Me.identificacaoRpsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
    Public Property DataEmissaoRps() As Date
        Get
            Return Me.dataEmissaoRpsField
        End Get
        Set
            Me.dataEmissaoRpsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property DataEmissaoRpsSpecified() As Boolean
        Get
            Return Me.dataEmissaoRpsFieldSpecified
        End Get
        Set
            Me.dataEmissaoRpsFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property NaturezaOperacao() As SByte
        Get
            Return Me.naturezaOperacaoField
        End Get
        Set
            Me.naturezaOperacaoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property RegimeEspecialTributacao() As SByte
        Get
            Return Me.regimeEspecialTributacaoField
        End Get
        Set
            Me.regimeEspecialTributacaoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property RegimeEspecialTributacaoSpecified() As Boolean
        Get
            Return Me.regimeEspecialTributacaoFieldSpecified
        End Get
        Set
            Me.regimeEspecialTributacaoFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property OptanteSimplesNacional() As SByte
        Get
            Return Me.optanteSimplesNacionalField
        End Get
        Set
            Me.optanteSimplesNacionalField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property IncentivadorCultural() As SByte
        Get
            Return Me.incentivadorCulturalField
        End Get
        Set
            Me.incentivadorCulturalField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Competencia() As Date
        Get
            Return Me.competenciaField
        End Get
        Set
            Me.competenciaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
    Public Property NfseSubstituida() As String
        Get
            Return Me.nfseSubstituidaField
        End Get
        Set
            Me.nfseSubstituidaField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property OutrasInformacoes() As String
        Get
            Return Me.outrasInformacoesField
        End Get
        Set
            Me.outrasInformacoesField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Servico() As tcDadosServico
        Get
            Return Me.servicoField
        End Get
        Set
            Me.servicoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ValorCredito() As Decimal
        Get
            Return Me.valorCreditoField
        End Get
        Set
            Me.valorCreditoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ValorCreditoSpecified() As Boolean
        Get
            Return Me.valorCreditoFieldSpecified
        End Get
        Set
            Me.valorCreditoFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property PrestadorServico() As tcDadosPrestador
        Get
            Return Me.prestadorServicoField
        End Get
        Set
            Me.prestadorServicoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TomadorServico() As tcDadosTomador
        Get
            Return Me.tomadorServicoField
        End Get
        Set
            Me.tomadorServicoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property IntermediarioServico() As tcIdentificacaoIntermediarioServico
        Get
            Return Me.intermediarioServicoField
        End Get
        Set
            Me.intermediarioServicoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property OrgaoGerador() As tcIdentificacaoOrgaoGerador
        Get
            Return Me.orgaoGeradorField
        End Get
        Set
            Me.orgaoGeradorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ConstrucaoCivil() As tcDadosConstrucaoCivil
        Get
            Return Me.construcaoCivilField
        End Get
        Set
            Me.construcaoCivilField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcIdentificacaoRps
    
    Private numeroField As String
    
    Private serieField As String
    
    Private tipoField As SByte
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
    Public Property Numero() As String
        Get
            Return Me.numeroField
        End Get
        Set
            Me.numeroField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Serie() As String
        Get
            Return Me.serieField
        End Get
        Set
            Me.serieField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Tipo() As SByte
        Get
            Return Me.tipoField
        End Get
        Set
            Me.tipoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcInfRps
    
    Private identificacaoRpsField As tcIdentificacaoRps
    
    Private dataEmissaoField As Date
    
    Private naturezaOperacaoField As SByte
    
    Private regimeEspecialTributacaoField As SByte
    
    Private regimeEspecialTributacaoFieldSpecified As Boolean
    
    Private optanteSimplesNacionalField As SByte
    
    Private incentivadorCulturalField As SByte
    
    Private statusField As SByte
    
    Private rpsSubstituidoField As tcIdentificacaoRps
    
    Private servicoField As tcDadosServico
    
    Private prestadorField As tcIdentificacaoPrestador
    
    Private tomadorField As tcDadosTomador
    
    Private intermediarioServicoField As tcIdentificacaoIntermediarioServico
    
    Private construcaoCivilField As tcDadosConstrucaoCivil
    
    Private idField As String
    
    '''<remarks/>
    Public Property IdentificacaoRps() As tcIdentificacaoRps
        Get
            Return Me.identificacaoRpsField
        End Get
        Set
            Me.identificacaoRpsField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property DataEmissao() As Date
        Get
            Return Me.dataEmissaoField
        End Get
        Set
            Me.dataEmissaoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property NaturezaOperacao() As SByte
        Get
            Return Me.naturezaOperacaoField
        End Get
        Set
            Me.naturezaOperacaoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property RegimeEspecialTributacao() As SByte
        Get
            Return Me.regimeEspecialTributacaoField
        End Get
        Set
            Me.regimeEspecialTributacaoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property RegimeEspecialTributacaoSpecified() As Boolean
        Get
            Return Me.regimeEspecialTributacaoFieldSpecified
        End Get
        Set
            Me.regimeEspecialTributacaoFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property OptanteSimplesNacional() As SByte
        Get
            Return Me.optanteSimplesNacionalField
        End Get
        Set
            Me.optanteSimplesNacionalField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property IncentivadorCultural() As SByte
        Get
            Return Me.incentivadorCulturalField
        End Get
        Set
            Me.incentivadorCulturalField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Status() As SByte
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property RpsSubstituido() As tcIdentificacaoRps
        Get
            Return Me.rpsSubstituidoField
        End Get
        Set
            Me.rpsSubstituidoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Servico() As tcDadosServico
        Get
            Return Me.servicoField
        End Get
        Set
            Me.servicoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Prestador() As tcIdentificacaoPrestador
        Get
            Return Me.prestadorField
        End Get
        Set
            Me.prestadorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Tomador() As tcDadosTomador
        Get
            Return Me.tomadorField
        End Get
        Set
            Me.tomadorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property IntermediarioServico() As tcIdentificacaoIntermediarioServico
        Get
            Return Me.intermediarioServicoField
        End Get
        Set
            Me.intermediarioServicoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ConstrucaoCivil() As tcDadosConstrucaoCivil
        Get
            Return Me.construcaoCivilField
        End Get
        Set
            Me.construcaoCivilField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcDadosServico
    
    Private valoresField As tcValores
    
    Private itemListaServicoField As String
    
    Private codigoCnaeField As Integer
    
    Private codigoCnaeFieldSpecified As Boolean
    
    Private codigoTributacaoMunicipioField As String
    
    Private discriminacaoField As String
    
    Private codigoMunicipioField As Integer
    
    '''<remarks/>
    Public Property Valores() As tcValores
        Get
            Return Me.valoresField
        End Get
        Set
            Me.valoresField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ItemListaServico() As String
        Get
            Return Me.itemListaServicoField
        End Get
        Set
            Me.itemListaServicoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CodigoCnae() As Integer
        Get
            Return Me.codigoCnaeField
        End Get
        Set
            Me.codigoCnaeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property CodigoCnaeSpecified() As Boolean
        Get
            Return Me.codigoCnaeFieldSpecified
        End Get
        Set
            Me.codigoCnaeFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CodigoTributacaoMunicipio() As String
        Get
            Return Me.codigoTributacaoMunicipioField
        End Get
        Set
            Me.codigoTributacaoMunicipioField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Discriminacao() As String
        Get
            Return Me.discriminacaoField
        End Get
        Set
            Me.discriminacaoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CodigoMunicipio() As Integer
        Get
            Return Me.codigoMunicipioField
        End Get
        Set
            Me.codigoMunicipioField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcValores
    
    Private valorServicosField As Decimal
    
    Private valorDeducoesField As Decimal
    
    Private valorDeducoesFieldSpecified As Boolean
    
    Private valorPisField As Decimal
    
    Private valorPisFieldSpecified As Boolean
    
    Private valorCofinsField As Decimal
    
    Private valorCofinsFieldSpecified As Boolean
    
    Private valorInssField As Decimal
    
    Private valorInssFieldSpecified As Boolean
    
    Private valorIrField As Decimal
    
    Private valorIrFieldSpecified As Boolean
    
    Private valorCsllField As Decimal
    
    Private valorCsllFieldSpecified As Boolean
    
    Private issRetidoField As SByte
    
    Private valorIssField As Decimal
    
    Private valorIssFieldSpecified As Boolean
    
    Private valorIssRetidoField As Decimal
    
    Private valorIssRetidoFieldSpecified As Boolean
    
    Private outrasRetencoesField As Decimal
    
    Private outrasRetencoesFieldSpecified As Boolean
    
    Private baseCalculoField As Decimal
    
    Private baseCalculoFieldSpecified As Boolean
    
    Private aliquotaField As Decimal
    
    Private aliquotaFieldSpecified As Boolean
    
    Private valorLiquidoNfseField As Decimal
    
    Private valorLiquidoNfseFieldSpecified As Boolean
    
    Private descontoIncondicionadoField As Decimal
    
    Private descontoIncondicionadoFieldSpecified As Boolean
    
    Private descontoCondicionadoField As Decimal
    
    Private descontoCondicionadoFieldSpecified As Boolean
    
    '''<remarks/>
    Public Property ValorServicos() As Decimal
        Get
            Return Me.valorServicosField
        End Get
        Set
            Me.valorServicosField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ValorDeducoes() As Decimal
        Get
            Return Me.valorDeducoesField
        End Get
        Set
            Me.valorDeducoesField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ValorDeducoesSpecified() As Boolean
        Get
            Return Me.valorDeducoesFieldSpecified
        End Get
        Set
            Me.valorDeducoesFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ValorPis() As Decimal
        Get
            Return Me.valorPisField
        End Get
        Set
            Me.valorPisField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ValorPisSpecified() As Boolean
        Get
            Return Me.valorPisFieldSpecified
        End Get
        Set
            Me.valorPisFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ValorCofins() As Decimal
        Get
            Return Me.valorCofinsField
        End Get
        Set
            Me.valorCofinsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ValorCofinsSpecified() As Boolean
        Get
            Return Me.valorCofinsFieldSpecified
        End Get
        Set
            Me.valorCofinsFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ValorInss() As Decimal
        Get
            Return Me.valorInssField
        End Get
        Set
            Me.valorInssField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ValorInssSpecified() As Boolean
        Get
            Return Me.valorInssFieldSpecified
        End Get
        Set
            Me.valorInssFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ValorIr() As Decimal
        Get
            Return Me.valorIrField
        End Get
        Set
            Me.valorIrField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ValorIrSpecified() As Boolean
        Get
            Return Me.valorIrFieldSpecified
        End Get
        Set
            Me.valorIrFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ValorCsll() As Decimal
        Get
            Return Me.valorCsllField
        End Get
        Set
            Me.valorCsllField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ValorCsllSpecified() As Boolean
        Get
            Return Me.valorCsllFieldSpecified
        End Get
        Set
            Me.valorCsllFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property IssRetido() As SByte
        Get
            Return Me.issRetidoField
        End Get
        Set
            Me.issRetidoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ValorIss() As Decimal
        Get
            Return Me.valorIssField
        End Get
        Set
            Me.valorIssField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ValorIssSpecified() As Boolean
        Get
            Return Me.valorIssFieldSpecified
        End Get
        Set
            Me.valorIssFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ValorIssRetido() As Decimal
        Get
            Return Me.valorIssRetidoField
        End Get
        Set
            Me.valorIssRetidoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ValorIssRetidoSpecified() As Boolean
        Get
            Return Me.valorIssRetidoFieldSpecified
        End Get
        Set
            Me.valorIssRetidoFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property OutrasRetencoes() As Decimal
        Get
            Return Me.outrasRetencoesField
        End Get
        Set
            Me.outrasRetencoesField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property OutrasRetencoesSpecified() As Boolean
        Get
            Return Me.outrasRetencoesFieldSpecified
        End Get
        Set
            Me.outrasRetencoesFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property BaseCalculo() As Decimal
        Get
            Return Me.baseCalculoField
        End Get
        Set
            Me.baseCalculoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property BaseCalculoSpecified() As Boolean
        Get
            Return Me.baseCalculoFieldSpecified
        End Get
        Set
            Me.baseCalculoFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Aliquota() As Decimal
        Get
            Return Me.aliquotaField
        End Get
        Set
            Me.aliquotaField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property AliquotaSpecified() As Boolean
        Get
            Return Me.aliquotaFieldSpecified
        End Get
        Set
            Me.aliquotaFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ValorLiquidoNfse() As Decimal
        Get
            Return Me.valorLiquidoNfseField
        End Get
        Set
            Me.valorLiquidoNfseField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ValorLiquidoNfseSpecified() As Boolean
        Get
            Return Me.valorLiquidoNfseFieldSpecified
        End Get
        Set
            Me.valorLiquidoNfseFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property DescontoIncondicionado() As Decimal
        Get
            Return Me.descontoIncondicionadoField
        End Get
        Set
            Me.descontoIncondicionadoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property DescontoIncondicionadoSpecified() As Boolean
        Get
            Return Me.descontoIncondicionadoFieldSpecified
        End Get
        Set
            Me.descontoIncondicionadoFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property DescontoCondicionado() As Decimal
        Get
            Return Me.descontoCondicionadoField
        End Get
        Set
            Me.descontoCondicionadoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property DescontoCondicionadoSpecified() As Boolean
        Get
            Return Me.descontoCondicionadoFieldSpecified
        End Get
        Set
            Me.descontoCondicionadoFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcIdentificacaoPrestador
    
    Private cnpjField As String
    
    Private inscricaoMunicipalField As String
    
    '''<remarks/>
    Public Property Cnpj() As String
        Get
            Return Me.cnpjField
        End Get
        Set
            Me.cnpjField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property InscricaoMunicipal() As String
        Get
            Return Me.inscricaoMunicipalField
        End Get
        Set
            Me.inscricaoMunicipalField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcDadosTomador
    
    Private identificacaoTomadorField As tcIdentificacaoTomador
    
    Private razaoSocialField As String
    
    Private enderecoField As tcEndereco
    
    Private contatoField As tcContato
    
    '''<remarks/>
    Public Property IdentificacaoTomador() As tcIdentificacaoTomador
        Get
            Return Me.identificacaoTomadorField
        End Get
        Set
            Me.identificacaoTomadorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property RazaoSocial() As String
        Get
            Return Me.razaoSocialField
        End Get
        Set
            Me.razaoSocialField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Endereco() As tcEndereco
        Get
            Return Me.enderecoField
        End Get
        Set
            Me.enderecoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Contato() As tcContato
        Get
            Return Me.contatoField
        End Get
        Set
            Me.contatoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcIdentificacaoTomador
    
    Private cpfCnpjField As tcCpfCnpj
    
    Private inscricaoMunicipalField As String
    
    '''<remarks/>
    Public Property CpfCnpj() As tcCpfCnpj
        Get
            Return Me.cpfCnpjField
        End Get
        Set
            Me.cpfCnpjField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property InscricaoMunicipal() As String
        Get
            Return Me.inscricaoMunicipalField
        End Get
        Set
            Me.inscricaoMunicipalField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcCpfCnpj
    
    Private itemField As String
    
    Private itemElementNameField As ItemChoiceType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Cnpj", GetType(String)),  _
     System.Xml.Serialization.XmlElementAttribute("Cpf", GetType(String)),  _
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>  _
    Public Property Item() As String
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ItemElementName() As ItemChoiceType
        Get
            Return Me.itemElementNameField
        End Get
        Set
            Me.itemElementNameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IncludeInSchema:=false)>  _
Public Enum ItemChoiceType
    
    '''<remarks/>
    Cnpj
    
    '''<remarks/>
    Cpf
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcEndereco
    
    Private enderecoField As String
    
    Private numeroField As String
    
    Private complementoField As String
    
    Private bairroField As String
    
    Private codigoMunicipioField As Integer
    
    Private codigoMunicipioFieldSpecified As Boolean
    
    Private ufField As String
    
    Private cepField As Integer
    
    Private cepFieldSpecified As Boolean
    
    '''<remarks/>
    Public Property Endereco() As String
        Get
            Return Me.enderecoField
        End Get
        Set
            Me.enderecoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Numero() As String
        Get
            Return Me.numeroField
        End Get
        Set
            Me.numeroField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Complemento() As String
        Get
            Return Me.complementoField
        End Get
        Set
            Me.complementoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Bairro() As String
        Get
            Return Me.bairroField
        End Get
        Set
            Me.bairroField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CodigoMunicipio() As Integer
        Get
            Return Me.codigoMunicipioField
        End Get
        Set
            Me.codigoMunicipioField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property CodigoMunicipioSpecified() As Boolean
        Get
            Return Me.codigoMunicipioFieldSpecified
        End Get
        Set
            Me.codigoMunicipioFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Uf() As String
        Get
            Return Me.ufField
        End Get
        Set
            Me.ufField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Cep() As Integer
        Get
            Return Me.cepField
        End Get
        Set
            Me.cepField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property CepSpecified() As Boolean
        Get
            Return Me.cepFieldSpecified
        End Get
        Set
            Me.cepFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcContato
    
    Private telefoneField As String
    
    Private emailField As String
    
    '''<remarks/>
    Public Property Telefone() As String
        Get
            Return Me.telefoneField
        End Get
        Set
            Me.telefoneField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Email() As String
        Get
            Return Me.emailField
        End Get
        Set
            Me.emailField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcIdentificacaoIntermediarioServico
    
    Private razaoSocialField As String
    
    Private cpfCnpjField As tcCpfCnpj
    
    Private inscricaoMunicipalField As String
    
    '''<remarks/>
    Public Property RazaoSocial() As String
        Get
            Return Me.razaoSocialField
        End Get
        Set
            Me.razaoSocialField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CpfCnpj() As tcCpfCnpj
        Get
            Return Me.cpfCnpjField
        End Get
        Set
            Me.cpfCnpjField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property InscricaoMunicipal() As String
        Get
            Return Me.inscricaoMunicipalField
        End Get
        Set
            Me.inscricaoMunicipalField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcDadosConstrucaoCivil
    
    Private codigoObraField As String
    
    Private artField As String
    
    '''<remarks/>
    Public Property CodigoObra() As String
        Get
            Return Me.codigoObraField
        End Get
        Set
            Me.codigoObraField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Art() As String
        Get
            Return Me.artField
        End Get
        Set
            Me.artField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcRps
    
    Private infRpsField As tcInfRps
    
    '''<remarks/>
    Public Property InfRps() As tcInfRps
        Get
            Return Me.infRpsField
        End Get
        Set
            Me.infRpsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcLoteRps
    
    Private numeroLoteField As String
    
    Private cnpjField As String
    
    Private inscricaoMunicipalField As String
    
    Private quantidadeRpsField As Integer
    
    Private listaRpsField() As tcRps
    
    Private idField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
    Public Property NumeroLote() As String
        Get
            Return Me.numeroLoteField
        End Get
        Set
            Me.numeroLoteField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Cnpj() As String
        Get
            Return Me.cnpjField
        End Get
        Set
            Me.cnpjField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property InscricaoMunicipal() As String
        Get
            Return Me.inscricaoMunicipalField
        End Get
        Set
            Me.inscricaoMunicipalField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property QuantidadeRps() As Integer
        Get
            Return Me.quantidadeRpsField
        End Get
        Set
            Me.quantidadeRpsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Rps", IsNullable:=false)>  _
    Public Property ListaRps() As tcRps()
        Get
            Return Me.listaRpsField
        End Get
        Set
            Me.listaRpsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcMensagemRetorno
    
    Private codigoField As String
    
    Private mensagemField As String
    
    Private correcaoField As String
    
    '''<remarks/>
    Public Property Codigo() As String
        Get
            Return Me.codigoField
        End Get
        Set
            Me.codigoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Mensagem() As String
        Get
            Return Me.mensagemField
        End Get
        Set
            Me.mensagemField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Correcao() As String
        Get
            Return Me.correcaoField
        End Get
        Set
            Me.correcaoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcInfSubstituicaoNfse
    
    Private nfseSubstituidoraField As String
    
    Private idField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
    Public Property NfseSubstituidora() As String
        Get
            Return Me.nfseSubstituidoraField
        End Get
        Set
            Me.nfseSubstituidoraField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcSubstituicaoNfse
    
    Private substituicaoNfseField As tcInfSubstituicaoNfse
    
    '''<remarks/>
    Public Property SubstituicaoNfse() As tcInfSubstituicaoNfse
        Get
            Return Me.substituicaoNfseField
        End Get
        Set
            Me.substituicaoNfseField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcIdentificacaoNfse
    
    Private numeroField As String
    
    Private cnpjField As String
    
    Private inscricaoMunicipalField As String
    
    Private codigoMunicipioField As Integer
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
    Public Property Numero() As String
        Get
            Return Me.numeroField
        End Get
        Set
            Me.numeroField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Cnpj() As String
        Get
            Return Me.cnpjField
        End Get
        Set
            Me.cnpjField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property InscricaoMunicipal() As String
        Get
            Return Me.inscricaoMunicipalField
        End Get
        Set
            Me.inscricaoMunicipalField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CodigoMunicipio() As Integer
        Get
            Return Me.codigoMunicipioField
        End Get
        Set
            Me.codigoMunicipioField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcInfPedidoCancelamento
    
    Private identificacaoNfseField As tcIdentificacaoNfse
    
    Private codigoCancelamentoField As String
    
    Private idField As String
    
    '''<remarks/>
    Public Property IdentificacaoNfse() As tcIdentificacaoNfse
        Get
            Return Me.identificacaoNfseField
        End Get
        Set
            Me.identificacaoNfseField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CodigoCancelamento() As String
        Get
            Return Me.codigoCancelamentoField
        End Get
        Set
            Me.codigoCancelamentoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcPedidoCancelamento
    
    Private infPedidoCancelamentoField As tcInfPedidoCancelamento
    
    '''<remarks/>
    Public Property InfPedidoCancelamento() As tcInfPedidoCancelamento
        Get
            Return Me.infPedidoCancelamentoField
        End Get
        Set
            Me.infPedidoCancelamentoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcConfirmacaoCancelamento
    
    Private pedidoField As tcPedidoCancelamento
    
    Private dataHoraCancelamentoField As Date
    
    Private idField As String
    
    '''<remarks/>
    Public Property Pedido() As tcPedidoCancelamento
        Get
            Return Me.pedidoField
        End Get
        Set
            Me.pedidoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property DataHoraCancelamento() As Date
        Get
            Return Me.dataHoraCancelamentoField
        End Get
        Set
            Me.dataHoraCancelamentoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcCancelamentoNfse
    
    Private confirmacaoField As tcConfirmacaoCancelamento
    
    '''<remarks/>
    Public Property Confirmacao() As tcConfirmacaoCancelamento
        Get
            Return Me.confirmacaoField
        End Get
        Set
            Me.confirmacaoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcIdentificacaoOrgaoGerador
    
    Private codigoMunicipioField As Integer
    
    Private ufField As String
    
    '''<remarks/>
    Public Property CodigoMunicipio() As Integer
        Get
            Return Me.codigoMunicipioField
        End Get
        Set
            Me.codigoMunicipioField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Uf() As String
        Get
            Return Me.ufField
        End Get
        Set
            Me.ufField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class tcDadosPrestador
    
    Private identificacaoPrestadorField As tcIdentificacaoPrestador
    
    Private razaoSocialField As String
    
    Private nomeFantasiaField As String
    
    Private enderecoField As tcEndereco
    
    Private contatoField As tcContato
    
    '''<remarks/>
    Public Property IdentificacaoPrestador() As tcIdentificacaoPrestador
        Get
            Return Me.identificacaoPrestadorField
        End Get
        Set
            Me.identificacaoPrestadorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property RazaoSocial() As String
        Get
            Return Me.razaoSocialField
        End Get
        Set
            Me.razaoSocialField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property NomeFantasia() As String
        Get
            Return Me.nomeFantasiaField
        End Get
        Set
            Me.nomeFantasiaField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Endereco() As tcEndereco
        Get
            Return Me.enderecoField
        End Get
        Set
            Me.enderecoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Contato() As tcContato
        Get
            Return Me.contatoField
        End Get
        Set
            Me.contatoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class ListaMensagemRetorno
    
    Private mensagemRetornoField() As tcMensagemRetorno
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("MensagemRetorno")>  _
    Public Property MensagemRetorno() As tcMensagemRetorno()
        Get
            Return Me.mensagemRetornoField
        End Get
        Set
            Me.mensagemRetornoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class EnviarLoteRpsResposta
    
    Private itemsField() As Object
    
    Private itemsElementNameField() As ItemsChoiceType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("DataRecebimento", GetType(Date)),  _
     System.Xml.Serialization.XmlElementAttribute("ListaMensagemRetorno", GetType(ListaMensagemRetorno)),  _
     System.Xml.Serialization.XmlElementAttribute("NumeroLote", GetType(String), DataType:="nonNegativeInteger"),  _
     System.Xml.Serialization.XmlElementAttribute("Protocolo", GetType(String)),  _
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>  _
    Public Property Items() As Object()
        Get
            Return Me.itemsField
        End Get
        Set
            Me.itemsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),  _
     System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ItemsElementName() As ItemsChoiceType()
        Get
            Return Me.itemsElementNameField
        End Get
        Set
            Me.itemsElementNameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IncludeInSchema:=false)>  _
Public Enum ItemsChoiceType
    
    '''<remarks/>
    DataRecebimento
    
    '''<remarks/>
    ListaMensagemRetorno
    
    '''<remarks/>
    NumeroLote
    
    '''<remarks/>
    Protocolo
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class EnviarLoteRpsEnvio
    
    Private loteRpsField As tcLoteRps
    
    '''<remarks/>
    Public Property LoteRps() As tcLoteRps
        Get
            Return Me.loteRpsField
        End Get
        Set
            Me.loteRpsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class ConsultarSituacaoLoteRpsResposta
    
    Private itemsField() As Object
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("ListaMensagemRetorno", GetType(ListaMensagemRetorno)),  _
     System.Xml.Serialization.XmlElementAttribute("NumeroLote", GetType(String), DataType:="nonNegativeInteger"),  _
     System.Xml.Serialization.XmlElementAttribute("Situacao", GetType(SByte))>  _
    Public Property Items() As Object()
        Get
            Return Me.itemsField
        End Get
        Set
            Me.itemsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class ConsultarSituacaoLoteRpsEnvio
    
    Private prestadorField As tcIdentificacaoPrestador
    
    Private protocoloField As String
    
    '''<remarks/>
    Public Property Prestador() As tcIdentificacaoPrestador
        Get
            Return Me.prestadorField
        End Get
        Set
            Me.prestadorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Protocolo() As String
        Get
            Return Me.protocoloField
        End Get
        Set
            Me.protocoloField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class ConsultarNfseRpsResposta
    
    Private itemField As Object
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("CompNfse", GetType(tcCompNfse)),  _
     System.Xml.Serialization.XmlElementAttribute("ListaMensagemRetorno", GetType(ListaMensagemRetorno))>  _
    Public Property Item() As Object
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class ConsultarNfseRpsEnvio
    
    Private identificacaoRpsField As tcIdentificacaoRps
    
    Private prestadorField As tcIdentificacaoPrestador
    
    '''<remarks/>
    Public Property IdentificacaoRps() As tcIdentificacaoRps
        Get
            Return Me.identificacaoRpsField
        End Get
        Set
            Me.identificacaoRpsField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Prestador() As tcIdentificacaoPrestador
        Get
            Return Me.prestadorField
        End Get
        Set
            Me.prestadorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class ConsultarNfseResposta
    
    Private itemField As Object
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("ListaMensagemRetorno", GetType(ListaMensagemRetorno)),  _
     System.Xml.Serialization.XmlElementAttribute("ListaNfse", GetType(ConsultarNfseRespostaListaNfse))>  _
    Public Property Item() As Object
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class ConsultarNfseRespostaListaNfse
    
    Private compNfseField() As tcCompNfse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("CompNfse")>  _
    Public Property CompNfse() As tcCompNfse()
        Get
            Return Me.compNfseField
        End Get
        Set
            Me.compNfseField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class ConsultarNfseEnvio
    
    Private prestadorField As tcIdentificacaoPrestador
    
    Private numeroNfseField As String
    
    Private periodoEmissaoField As ConsultarNfseEnvioPeriodoEmissao
    
    Private tomadorField As tcIdentificacaoTomador
    
    Private intermediarioServicoField As tcIdentificacaoIntermediarioServico
    
    '''<remarks/>
    Public Property Prestador() As tcIdentificacaoPrestador
        Get
            Return Me.prestadorField
        End Get
        Set
            Me.prestadorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
    Public Property NumeroNfse() As String
        Get
            Return Me.numeroNfseField
        End Get
        Set
            Me.numeroNfseField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property PeriodoEmissao() As ConsultarNfseEnvioPeriodoEmissao
        Get
            Return Me.periodoEmissaoField
        End Get
        Set
            Me.periodoEmissaoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Tomador() As tcIdentificacaoTomador
        Get
            Return Me.tomadorField
        End Get
        Set
            Me.tomadorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property IntermediarioServico() As tcIdentificacaoIntermediarioServico
        Get
            Return Me.intermediarioServicoField
        End Get
        Set
            Me.intermediarioServicoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class ConsultarNfseEnvioPeriodoEmissao
    
    Private dataInicialField As Date
    
    Private dataFinalField As Date
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
    Public Property DataInicial() As Date
        Get
            Return Me.dataInicialField
        End Get
        Set
            Me.dataInicialField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
    Public Property DataFinal() As Date
        Get
            Return Me.dataFinalField
        End Get
        Set
            Me.dataFinalField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class ConsultarLoteRpsResposta
    
    Private itemField As Object
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("ListaMensagemRetorno", GetType(ListaMensagemRetorno)),  _
     System.Xml.Serialization.XmlElementAttribute("ListaNfse", GetType(ConsultarLoteRpsRespostaListaNfse))>  _
    Public Property Item() As Object
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd")>  _
Partial Public Class ConsultarLoteRpsRespostaListaNfse
    
    Private compNfseField() As tcCompNfse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("CompNfse")>  _
    Public Property CompNfse() As tcCompNfse()
        Get
            Return Me.compNfseField
        End Get
        Set
            Me.compNfseField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class ConsultarLoteRpsEnvio
    
    Private prestadorField As tcIdentificacaoPrestador
    
    Private protocoloField As String
    
    '''<remarks/>
    Public Property Prestador() As tcIdentificacaoPrestador
        Get
            Return Me.prestadorField
        End Get
        Set
            Me.prestadorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Protocolo() As String
        Get
            Return Me.protocoloField
        End Get
        Set
            Me.protocoloField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class CancelarNfseResposta
    
    Private itemField As Object
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Cancelamento", GetType(tcCancelamentoNfse)),  _
     System.Xml.Serialization.XmlElementAttribute("ListaMensagemRetorno", GetType(ListaMensagemRetorno))>  _
    Public Property Item() As Object
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", IsNullable:=false)>  _
Partial Public Class CancelarNfseEnvio
    
    Private pedidoField As tcPedidoCancelamento
    
    '''<remarks/>
    Public Property Pedido() As tcPedidoCancelamento
        Get
            Return Me.pedidoField
        End Get
        Set
            Me.pedidoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.abrasf.org.br/nfse.xsd"), _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.abrasf.org.br/nfse.xsd", IsNullable:=False)> _
Partial Public Class cabecalho

    Private versaoDadosField As String

    Private versaoField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="token")> _
    Public Property versaoDados() As String
        Get
            Return Me.versaoDadosField
        End Get
        Set(ByVal value As String)
            Me.versaoDadosField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")> _
    Public Property versao() As String
        Get
            Return Me.versaoField
        End Get
        Set(ByVal value As String)
            Me.versaoField = value
        End Set
    End Property
End Class
