'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace br.com.nfeosasco.www
    
    'CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_INotaFiscalEletronicaServico", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResponseBase)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(RequestBase))>  _
    Partial Public Class NotaFiscalEletronicaServico
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EmitirOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CancelarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.nfseabrasf.My.MySettings.Default.nfseabrasf_br_com_nfeosasco_www_NotaFiscalEletronicaServico
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EmitirCompleted As EmitirCompletedEventHandler
        
        '''<remarks/>
        Public Event CancelarCompleted As CancelarCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INotaFiscalEletronicaServico/Emitir", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Emitir(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As EmissaoNotaFiscalRequest) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> EmissaoNotaFiscalResponse
            Dim results() As Object = Me.Invoke("Emitir", New Object() {request})
            Return CType(results(0),EmissaoNotaFiscalResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EmitirAsync(ByVal request As EmissaoNotaFiscalRequest)
            Me.EmitirAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EmitirAsync(ByVal request As EmissaoNotaFiscalRequest, ByVal userState As Object)
            If (Me.EmitirOperationCompleted Is Nothing) Then
                Me.EmitirOperationCompleted = AddressOf Me.OnEmitirOperationCompleted
            End If
            Me.InvokeAsync("Emitir", New Object() {request}, Me.EmitirOperationCompleted, userState)
        End Sub
        
        Private Sub OnEmitirOperationCompleted(ByVal arg As Object)
            If (Not (Me.EmitirCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EmitirCompleted(Me, New EmitirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INotaFiscalEletronicaServico/Cancelar", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Cancelar(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As CancelamentoNotaFiscalRequest) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> CancelamentoNotaFiscalResponse
            Dim results() As Object = Me.Invoke("Cancelar", New Object() {request})
            Return CType(results(0),CancelamentoNotaFiscalResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CancelarAsync(ByVal request As CancelamentoNotaFiscalRequest)
            Me.CancelarAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelarAsync(ByVal request As CancelamentoNotaFiscalRequest, ByVal userState As Object)
            If (Me.CancelarOperationCompleted Is Nothing) Then
                Me.CancelarOperationCompleted = AddressOf Me.OnCancelarOperationCompleted
            End If
            Me.InvokeAsync("Cancelar", New Object() {request}, Me.CancelarOperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelarOperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelarCompleted(Me, New CancelarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Rgm.Eissnfe.Negocio.WebServices.Mensagem")>  _
    Partial Public Class EmissaoNotaFiscalRequest
        Inherits RequestBase
        
        Private notaFiscalField As NotaFiscalDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NotaFiscal() As NotaFiscalDTO
            Get
                Return Me.notaFiscalField
            End Get
            Set
                Me.notaFiscalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Rgm.Eissnfe.Dominio.DataTransferObject.Pr"& _ 
        "estador")>  _
    Partial Public Class NotaFiscalDTO
        
        Private aliquotaField As System.Nullable(Of Decimal)
        
        Private atividadeField As String
        
        Private chaveAutenticacaoField As String
        
        Private homologacaoField As Boolean
        
        Private informacoesAdicionaisField As String
        
        Private notificarTomadorPorEmailField As Boolean
        
        Private substituicaoTributariaField As Boolean
        
        Private tomadorField As PessoaDTO
        
        Private tomadorEstrangeiroField As Boolean
        
        Private tomadorEstrangeiroFieldSpecified As Boolean
        
        Private valorField As Decimal
        
        Private valorDeducaoField As System.Nullable(Of Decimal)
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Aliquota() As System.Nullable(Of Decimal)
            Get
                Return Me.aliquotaField
            End Get
            Set
                Me.aliquotaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Atividade() As String
            Get
                Return Me.atividadeField
            End Get
            Set
                Me.atividadeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ChaveAutenticacao() As String
            Get
                Return Me.chaveAutenticacaoField
            End Get
            Set
                Me.chaveAutenticacaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Homologacao() As Boolean
            Get
                Return Me.homologacaoField
            End Get
            Set
                Me.homologacaoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property InformacoesAdicionais() As String
            Get
                Return Me.informacoesAdicionaisField
            End Get
            Set
                Me.informacoesAdicionaisField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NotificarTomadorPorEmail() As Boolean
            Get
                Return Me.notificarTomadorPorEmailField
            End Get
            Set
                Me.notificarTomadorPorEmailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SubstituicaoTributaria() As Boolean
            Get
                Return Me.substituicaoTributariaField
            End Get
            Set
                Me.substituicaoTributariaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Tomador() As PessoaDTO
            Get
                Return Me.tomadorField
            End Get
            Set
                Me.tomadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TomadorEstrangeiro() As Boolean
            Get
                Return Me.tomadorEstrangeiroField
            End Get
            Set
                Me.tomadorEstrangeiroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TomadorEstrangeiroSpecified() As Boolean
            Get
                Return Me.tomadorEstrangeiroFieldSpecified
            End Get
            Set
                Me.tomadorEstrangeiroFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ValorDeducao() As System.Nullable(Of Decimal)
            Get
                Return Me.valorDeducaoField
            End Get
            Set
                Me.valorDeducaoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Rgm.Eissnfe.Dominio.DataTransferObject.Co"& _ 
        "ntribuinte")>  _
    Partial Public Class PessoaDTO
        
        Private cNPJField As String
        
        Private cPFField As String
        
        Private dDDField As String
        
        Private emailField As String
        
        Private enderecoField As EnderecoDTO
        
        Private inscricaoMunicipalField As String
        
        Private nomeField As String
        
        Private telefoneField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CNPJ() As String
            Get
                Return Me.cNPJField
            End Get
            Set
                Me.cNPJField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CPF() As String
            Get
                Return Me.cPFField
            End Get
            Set
                Me.cPFField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DDD() As String
            Get
                Return Me.dDDField
            End Get
            Set
                Me.dDDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Endereco() As EnderecoDTO
            Get
                Return Me.enderecoField
            End Get
            Set
                Me.enderecoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property InscricaoMunicipal() As String
            Get
                Return Me.inscricaoMunicipalField
            End Get
            Set
                Me.inscricaoMunicipalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Nome() As String
            Get
                Return Me.nomeField
            End Get
            Set
                Me.nomeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Telefone() As String
            Get
                Return Me.telefoneField
            End Get
            Set
                Me.telefoneField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Rgm.Eissnfe.Dominio.DataTransferObject.Co"& _ 
        "ntribuinte")>  _
    Partial Public Class EnderecoDTO
        
        Private bairroField As String
        
        Private cEPField As String
        
        Private cidadeField As String
        
        Private complementoField As String
        
        Private estadoField As String
        
        Private logradouroField As String
        
        Private numeroField As String
        
        Private paisField As String
        
        Private tipoLogradouroField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Bairro() As String
            Get
                Return Me.bairroField
            End Get
            Set
                Me.bairroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CEP() As String
            Get
                Return Me.cEPField
            End Get
            Set
                Me.cEPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Cidade() As String
            Get
                Return Me.cidadeField
            End Get
            Set
                Me.cidadeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Complemento() As String
            Get
                Return Me.complementoField
            End Get
            Set
                Me.complementoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Logradouro() As String
            Get
                Return Me.logradouroField
            End Get
            Set
                Me.logradouroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Pais() As String
            Get
                Return Me.paisField
            End Get
            Set
                Me.paisField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TipoLogradouro() As String
            Get
                Return Me.tipoLogradouroField
            End Get
            Set
                Me.tipoLogradouroField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Rgm.Eissnfe.Dominio.DataTransferObject.Pr"& _ 
        "estador")>  _
    Partial Public Class NotaFiscalGeradaDTO
        
        Private autenticadorField As String
        
        Private numeroField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Autenticador() As String
            Get
                Return Me.autenticadorField
            End Get
            Set
                Me.autenticadorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(CancelamentoNotaFiscalResponse)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EmissaoNotaFiscalResponse)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Rgm.Eissnfe.Negocio.WebServices.Mensagem")>  _
    Partial Public Class ResponseBase
        
        Private erroField As Boolean
        
        Private erroFieldSpecified As Boolean
        
        Private mensagemErroField As String
        
        '''<remarks/>
        Public Property Erro() As Boolean
            Get
                Return Me.erroField
            End Get
            Set
                Me.erroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ErroSpecified() As Boolean
            Get
                Return Me.erroFieldSpecified
            End Get
            Set
                Me.erroFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MensagemErro() As String
            Get
                Return Me.mensagemErroField
            End Get
            Set
                Me.mensagemErroField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Rgm.Eissnfe.Negocio.WebServices.Mensagem")>  _
    Partial Public Class CancelamentoNotaFiscalResponse
        Inherits ResponseBase
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Rgm.Eissnfe.Negocio.WebServices.Mensagem")>  _
    Partial Public Class EmissaoNotaFiscalResponse
        Inherits ResponseBase
        
        Private notaFiscalGeradaField As NotaFiscalGeradaDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NotaFiscalGerada() As NotaFiscalGeradaDTO
            Get
                Return Me.notaFiscalGeradaField
            End Get
            Set
                Me.notaFiscalGeradaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(CancelamentoNotaFiscalRequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EmissaoNotaFiscalRequest)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Rgm.Eissnfe.Negocio.WebServices.Mensagem")>  _
    Partial Public Class RequestBase
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Rgm.Eissnfe.Negocio.WebServices.Mensagem")>  _
    Partial Public Class CancelamentoNotaFiscalRequest
        Inherits RequestBase
        
        Private chaveAutenticacaoField As String
        
        Private homologacaoField As Boolean
        
        Private numeroNotaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ChaveAutenticacao() As String
            Get
                Return Me.chaveAutenticacaoField
            End Get
            Set
                Me.chaveAutenticacaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Homologacao() As Boolean
            Get
                Return Me.homologacaoField
            End Get
            Set
                Me.homologacaoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NumeroNota() As String
            Get
                Return Me.numeroNotaField
            End Get
            Set
                Me.numeroNotaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub EmitirCompletedEventHandler(ByVal sender As Object, ByVal e As EmitirCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EmitirCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EmissaoNotaFiscalResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EmissaoNotaFiscalResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub CancelarCompletedEventHandler(ByVal sender As Object, ByVal e As CancelarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CancelamentoNotaFiscalResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CancelamentoNotaFiscalResponse)
            End Get
        End Property
    End Class
End Namespace
