'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bhservicehomologacao
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ws.bhiss.pbh.gov.br", ConfigurationName:="bhservicehomologacao.nfse")>  _
    Public Interface nfse
        
        'CODEGEN: Generating message contract since the wrapper name (CancelarNfseRequest) of message CancelarNfseRequest does not match the default value (CancelarNfse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/CancelarNfse", ReplyAction:="*")>  _
        Function CancelarNfse(ByVal request As bhservicehomologacao.CancelarNfseRequest) As bhservicehomologacao.CancelarNfseResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarLoteRpsRequest) of message ConsultarLoteRpsRequest does not match the default value (ConsultarLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/ConsultarLoteRps", ReplyAction:="*")>  _
        Function ConsultarLoteRps(ByVal request As bhservicehomologacao.ConsultarLoteRpsRequest) As bhservicehomologacao.ConsultarLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarNfseRequest) of message ConsultarNfseRequest does not match the default value (ConsultarNfse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/ConsultarNfse", ReplyAction:="*")>  _
        Function ConsultarNfse(ByVal request As bhservicehomologacao.ConsultarNfseRequest) As bhservicehomologacao.ConsultarNfseResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarNfsePorFaixaRequest) of message ConsultarNfsePorFaixaRequest does not match the default value (ConsultarNfsePorFaixa)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/ConsultarNfsePorFaixa", ReplyAction:="*")>  _
        Function ConsultarNfsePorFaixa(ByVal request As bhservicehomologacao.ConsultarNfsePorFaixaRequest) As bhservicehomologacao.ConsultarNfsePorFaixaResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarNfsePorRpsRequest) of message ConsultarNfsePorRpsRequest does not match the default value (ConsultarNfsePorRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/ConsultarNfsePorRps", ReplyAction:="*")>  _
        Function ConsultarNfsePorRps(ByVal request As bhservicehomologacao.ConsultarNfsePorRpsRequest) As bhservicehomologacao.ConsultarNfsePorRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarSituacaoLoteRpsRequest) of message ConsultarSituacaoLoteRpsRequest does not match the default value (ConsultarSituacaoLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/ConsultarSituacaoLoteRps", ReplyAction:="*")>  _
        Function ConsultarSituacaoLoteRps(ByVal request As bhservicehomologacao.ConsultarSituacaoLoteRpsRequest) As bhservicehomologacao.ConsultarSituacaoLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (RecepcionarLoteRpsRequest) of message RecepcionarLoteRpsRequest does not match the default value (RecepcionarLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/RecepcionarLoteRps", ReplyAction:="*")>  _
        Function RecepcionarLoteRps(ByVal request As bhservicehomologacao.RecepcionarLoteRpsRequest) As bhservicehomologacao.RecepcionarLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (GerarNfseRequest) of message GerarNfseRequest does not match the default value (GerarNfse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/GerarNfse", ReplyAction:="*")>  _
        Function GerarNfse(ByVal request As bhservicehomologacao.GerarNfseRequest) As bhservicehomologacao.GerarNfseResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelarNfseRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class CancelarNfseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelarNfseResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class CancelarNfseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarLoteRpsRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarLoteRpsResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfseRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfseResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorFaixaRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorFaixaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorFaixaResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorFaixaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorRpsRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorRpsResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarSituacaoLoteRpsRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarSituacaoLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarSituacaoLoteRpsResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarSituacaoLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecepcionarLoteRpsRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class RecepcionarLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecepcionarLoteRpsResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class RecepcionarLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GerarNfseRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class GerarNfseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GerarNfseResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class GerarNfseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface nfseChannel
        Inherits bhservicehomologacao.nfse, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class nfseClient
        Inherits System.ServiceModel.ClientBase(Of bhservicehomologacao.nfse)
        Implements bhservicehomologacao.nfse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function bhservicehomologacao_nfse_CancelarNfse(ByVal request As bhservicehomologacao.CancelarNfseRequest) As bhservicehomologacao.CancelarNfseResponse Implements bhservicehomologacao.nfse.CancelarNfse
            Return MyBase.Channel.CancelarNfse(request)
        End Function
        
        Public Function CancelarNfse(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As bhservicehomologacao.CancelarNfseRequest = New bhservicehomologacao.CancelarNfseRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As bhservicehomologacao.CancelarNfseResponse = CType(Me,bhservicehomologacao.nfse).CancelarNfse(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function bhservicehomologacao_nfse_ConsultarLoteRps(ByVal request As bhservicehomologacao.ConsultarLoteRpsRequest) As bhservicehomologacao.ConsultarLoteRpsResponse Implements bhservicehomologacao.nfse.ConsultarLoteRps
            Return MyBase.Channel.ConsultarLoteRps(request)
        End Function
        
        Public Function ConsultarLoteRps(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As bhservicehomologacao.ConsultarLoteRpsRequest = New bhservicehomologacao.ConsultarLoteRpsRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As bhservicehomologacao.ConsultarLoteRpsResponse = CType(Me,bhservicehomologacao.nfse).ConsultarLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function bhservicehomologacao_nfse_ConsultarNfse(ByVal request As bhservicehomologacao.ConsultarNfseRequest) As bhservicehomologacao.ConsultarNfseResponse Implements bhservicehomologacao.nfse.ConsultarNfse
            Return MyBase.Channel.ConsultarNfse(request)
        End Function
        
        Public Function ConsultarNfse(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As bhservicehomologacao.ConsultarNfseRequest = New bhservicehomologacao.ConsultarNfseRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As bhservicehomologacao.ConsultarNfseResponse = CType(Me,bhservicehomologacao.nfse).ConsultarNfse(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function bhservicehomologacao_nfse_ConsultarNfsePorFaixa(ByVal request As bhservicehomologacao.ConsultarNfsePorFaixaRequest) As bhservicehomologacao.ConsultarNfsePorFaixaResponse Implements bhservicehomologacao.nfse.ConsultarNfsePorFaixa
            Return MyBase.Channel.ConsultarNfsePorFaixa(request)
        End Function
        
        Public Function ConsultarNfsePorFaixa(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As bhservicehomologacao.ConsultarNfsePorFaixaRequest = New bhservicehomologacao.ConsultarNfsePorFaixaRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As bhservicehomologacao.ConsultarNfsePorFaixaResponse = CType(Me,bhservicehomologacao.nfse).ConsultarNfsePorFaixa(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function bhservicehomologacao_nfse_ConsultarNfsePorRps(ByVal request As bhservicehomologacao.ConsultarNfsePorRpsRequest) As bhservicehomologacao.ConsultarNfsePorRpsResponse Implements bhservicehomologacao.nfse.ConsultarNfsePorRps
            Return MyBase.Channel.ConsultarNfsePorRps(request)
        End Function
        
        Public Function ConsultarNfsePorRps(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As bhservicehomologacao.ConsultarNfsePorRpsRequest = New bhservicehomologacao.ConsultarNfsePorRpsRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As bhservicehomologacao.ConsultarNfsePorRpsResponse = CType(Me,bhservicehomologacao.nfse).ConsultarNfsePorRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function bhservicehomologacao_nfse_ConsultarSituacaoLoteRps(ByVal request As bhservicehomologacao.ConsultarSituacaoLoteRpsRequest) As bhservicehomologacao.ConsultarSituacaoLoteRpsResponse Implements bhservicehomologacao.nfse.ConsultarSituacaoLoteRps
            Return MyBase.Channel.ConsultarSituacaoLoteRps(request)
        End Function
        
        Public Function ConsultarSituacaoLoteRps(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As bhservicehomologacao.ConsultarSituacaoLoteRpsRequest = New bhservicehomologacao.ConsultarSituacaoLoteRpsRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As bhservicehomologacao.ConsultarSituacaoLoteRpsResponse = CType(Me,bhservicehomologacao.nfse).ConsultarSituacaoLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function bhservicehomologacao_nfse_RecepcionarLoteRps(ByVal request As bhservicehomologacao.RecepcionarLoteRpsRequest) As bhservicehomologacao.RecepcionarLoteRpsResponse Implements bhservicehomologacao.nfse.RecepcionarLoteRps
            Return MyBase.Channel.RecepcionarLoteRps(request)
        End Function
        
        Public Function RecepcionarLoteRps(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As bhservicehomologacao.RecepcionarLoteRpsRequest = New bhservicehomologacao.RecepcionarLoteRpsRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As bhservicehomologacao.RecepcionarLoteRpsResponse = CType(Me,bhservicehomologacao.nfse).RecepcionarLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function bhservicehomologacao_nfse_GerarNfse(ByVal request As bhservicehomologacao.GerarNfseRequest) As bhservicehomologacao.GerarNfseResponse Implements bhservicehomologacao.nfse.GerarNfse
            Return MyBase.Channel.GerarNfse(request)
        End Function
        
        Public Function GerarNfse(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As bhservicehomologacao.GerarNfseRequest = New bhservicehomologacao.GerarNfseRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As bhservicehomologacao.GerarNfseResponse = CType(Me,bhservicehomologacao.nfse).GerarNfse(inValue)
            Return retVal.outputXML
        End Function
    End Class
End Namespace
