'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace br.gov.ba.salvador.sefaz.nfsehml2
    
    'CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IConsultaNfseRPS", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ConsultaNfseRPS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ConsultarNfseRPSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarNfseRPSComplementarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.nfseabrasf.My.MySettings.Default.nfseabrasf_br_gov_ba_salvador_sefaz_nfsehml2_ConsultaNfseRPS
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConsultarNfseRPSCompleted As ConsultarNfseRPSCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarNfseRPSComplementarCompleted As ConsultarNfseRPSComplementarCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConsultaNfseRPS/ConsultarNfseRPS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarNfseRPS(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal consultaxml As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("ConsultarNfseRPS", New Object() {consultaxml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfseRPSAsync(ByVal consultaxml As String)
            Me.ConsultarNfseRPSAsync(consultaxml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfseRPSAsync(ByVal consultaxml As String, ByVal userState As Object)
            If (Me.ConsultarNfseRPSOperationCompleted Is Nothing) Then
                Me.ConsultarNfseRPSOperationCompleted = AddressOf Me.OnConsultarNfseRPSOperationCompleted
            End If
            Me.InvokeAsync("ConsultarNfseRPS", New Object() {consultaxml}, Me.ConsultarNfseRPSOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarNfseRPSOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarNfseRPSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarNfseRPSCompleted(Me, New ConsultarNfseRPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConsultaNfseRPS/ConsultarNfseRPSComplementar", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarNfseRPSComplementar(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal consultaxml As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("ConsultarNfseRPSComplementar", New Object() {consultaxml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfseRPSComplementarAsync(ByVal consultaxml As String)
            Me.ConsultarNfseRPSComplementarAsync(consultaxml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfseRPSComplementarAsync(ByVal consultaxml As String, ByVal userState As Object)
            If (Me.ConsultarNfseRPSComplementarOperationCompleted Is Nothing) Then
                Me.ConsultarNfseRPSComplementarOperationCompleted = AddressOf Me.OnConsultarNfseRPSComplementarOperationCompleted
            End If
            Me.InvokeAsync("ConsultarNfseRPSComplementar", New Object() {consultaxml}, Me.ConsultarNfseRPSComplementarOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarNfseRPSComplementarOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarNfseRPSComplementarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarNfseRPSComplementarCompleted(Me, New ConsultarNfseRPSComplementarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConsultarNfseRPSCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarNfseRPSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarNfseRPSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConsultarNfseRPSComplementarCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarNfseRPSComplementarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarNfseRPSComplementarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
