'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace br.gov.ba.salvador.sefaz.nfse
    
    'CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IEnvioLoteRPS", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnvioLoteRPS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnviarLoteRPSComplementarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarLoteRPSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.nfseabrasf.My.MySettings.Default.nfseabrasf_br_gov_ba_salvador_sefaz_nfse_EnvioLoteRPS
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnviarLoteRPSComplementarCompleted As EnviarLoteRPSComplementarCompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarLoteRPSCompleted As EnviarLoteRPSCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEnvioLoteRPS/EnviarLoteRPSComplementar", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarLoteRPSComplementar(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal loteXML As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal pxmlDadosComplementares As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("EnviarLoteRPSComplementar", New Object() {loteXML, pxmlDadosComplementares})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarLoteRPSComplementarAsync(ByVal loteXML As String, ByVal pxmlDadosComplementares As String)
            Me.EnviarLoteRPSComplementarAsync(loteXML, pxmlDadosComplementares, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarLoteRPSComplementarAsync(ByVal loteXML As String, ByVal pxmlDadosComplementares As String, ByVal userState As Object)
            If (Me.EnviarLoteRPSComplementarOperationCompleted Is Nothing) Then
                Me.EnviarLoteRPSComplementarOperationCompleted = AddressOf Me.OnEnviarLoteRPSComplementarOperationCompleted
            End If
            Me.InvokeAsync("EnviarLoteRPSComplementar", New Object() {loteXML, pxmlDadosComplementares}, Me.EnviarLoteRPSComplementarOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarLoteRPSComplementarOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarLoteRPSComplementarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarLoteRPSComplementarCompleted(Me, New EnviarLoteRPSComplementarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEnvioLoteRPS/EnviarLoteRPS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarLoteRPS(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal loteXML As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("EnviarLoteRPS", New Object() {loteXML})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarLoteRPSAsync(ByVal loteXML As String)
            Me.EnviarLoteRPSAsync(loteXML, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarLoteRPSAsync(ByVal loteXML As String, ByVal userState As Object)
            If (Me.EnviarLoteRPSOperationCompleted Is Nothing) Then
                Me.EnviarLoteRPSOperationCompleted = AddressOf Me.OnEnviarLoteRPSOperationCompleted
            End If
            Me.InvokeAsync("EnviarLoteRPS", New Object() {loteXML}, Me.EnviarLoteRPSOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarLoteRPSOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarLoteRPSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarLoteRPSCompleted(Me, New EnviarLoteRPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub EnviarLoteRPSComplementarCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarLoteRPSComplementarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarLoteRPSComplementarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub EnviarLoteRPSCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarLoteRPSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarLoteRPSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
