'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=asp22;Initial Catalog=SGEDic_Demo;Persist Security Info=True;User ID="& _ 
            "admin;Password=cacareco")>  _
        Public ReadOnly Property SGEDic_DemoConnectionString() As String
            Get
                Return CType(Me("SGEDic_DemoConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=asp22;Initial Catalog=SGEDados_Demo;Persist Security Info=True;User I"& _ 
            "D=sa;Password=SAPWD")>  _
        Public ReadOnly Property SGEDados_DemoConnectionString() As String
            Get
                Return CType(Me("SGEDados_DemoConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://bhissdigital.pbh.gov.br:443/bhiss-ws/nfse")>  _
        Public ReadOnly Property nfseabrasf_bhproducao_NfseWSService() As String
            Get
                Return CType(Me("nfseabrasf_bhproducao_NfseWSService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://bhisshomologa.pbh.gov.br:443/bhiss-ws/nfse")>  _
        Public ReadOnly Property nfseabrasf_bhhomologacao_NfseWSService() As String
            Get
                Return CType(Me("nfseabrasf_bhhomologacao_NfseWSService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://nfsehml.sefaz.salvador.ba.gov.br/EnvioLoteRPS/EnvioLoteRPS.svc")>  _
        Public ReadOnly Property nfseabrasf_br_gov_ba_salvador_sefaz_nfsehml_EnvioLoteRPS() As String
            Get
                Return CType(Me("nfseabrasf_br_gov_ba_salvador_sefaz_nfsehml_EnvioLoteRPS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://nfsehml.sefaz.salvador.ba.gov.br/ConsultaSituacaoLoteRPS/ConsultaSituacao"& _ 
            "LoteRPS.svc")>  _
        Public ReadOnly Property nfseabrasf_br_gov_ba_salvador_sefaz_nfsehml1_ConsultaSituacaoLoteRPS() As String
            Get
                Return CType(Me("nfseabrasf_br_gov_ba_salvador_sefaz_nfsehml1_ConsultaSituacaoLoteRPS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://nfsehml.sefaz.salvador.ba.gov.br/ConsultaNfseRPS/ConsultaNfseRPS.svc")>  _
        Public ReadOnly Property nfseabrasf_br_gov_ba_salvador_sefaz_nfsehml2_ConsultaNfseRPS() As String
            Get
                Return CType(Me("nfseabrasf_br_gov_ba_salvador_sefaz_nfsehml2_ConsultaNfseRPS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://nfsehml.sefaz.salvador.ba.gov.br/ConsultaLoteRPS/ConsultaLoteRPS.svc")>  _
        Public ReadOnly Property nfseabrasf_br_gov_ba_salvador_sefaz_nfsehml3_ConsultaLoteRPS() As String
            Get
                Return CType(Me("nfseabrasf_br_gov_ba_salvador_sefaz_nfsehml3_ConsultaLoteRPS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://nfse.sefaz.salvador.ba.gov.br/ENVIOLOTERPS/EnvioLoteRPS.svc")>  _
        Public ReadOnly Property nfseabrasf_br_gov_ba_salvador_sefaz_nfse_EnvioLoteRPS() As String
            Get
                Return CType(Me("nfseabrasf_br_gov_ba_salvador_sefaz_nfse_EnvioLoteRPS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://nfse.sefaz.salvador.ba.gov.br/CONSULTASITUACAOLOTERPS/ConsultaSituacaoLot"& _ 
            "eRPS.svc")>  _
        Public ReadOnly Property nfseabrasf_br_gov_ba_salvador_sefaz_nfse1_ConsultaSituacaoLoteRPS() As String
            Get
                Return CType(Me("nfseabrasf_br_gov_ba_salvador_sefaz_nfse1_ConsultaSituacaoLoteRPS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://nfse.sefaz.salvador.ba.gov.br/CONSULTANFSERPS/ConsultaNfseRPS.svc")>  _
        Public ReadOnly Property nfseabrasf_br_gov_ba_salvador_sefaz_nfse2_ConsultaNfseRPS() As String
            Get
                Return CType(Me("nfseabrasf_br_gov_ba_salvador_sefaz_nfse2_ConsultaNfseRPS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://nfse.sefaz.salvador.ba.gov.br/CONSULTALOTERPS/ConsultaLoteRPS.svc")>  _
        Public ReadOnly Property nfseabrasf_br_gov_ba_salvador_sefaz_nfse3_ConsultaLoteRPS() As String
            Get
                Return CType(Me("nfseabrasf_br_gov_ba_salvador_sefaz_nfse3_ConsultaLoteRPS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=ASP22;Initial Catalog=SGEDic_Demo;User ID=sa;Password=SAPWD")>  _
        Public ReadOnly Property SGEDic_DemoConnectionString1() As String
            Get
                Return CType(Me("SGEDic_DemoConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://producao.ginfes.com.br//ServiceGinfesImpl")>  _
        Public ReadOnly Property nfseabrasf_br_com_ginfes_producao_ServiceGinfesImplService() As String
            Get
                Return CType(Me("nfseabrasf_br_com_ginfes_producao_ServiceGinfesImplService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://homologacao.ginfes.com.br//ServiceGinfesImpl")>  _
        Public ReadOnly Property nfseabrasf_br_com_ginfes_homologacao_ServiceGinfesImplService() As String
            Get
                Return CType(Me("nfseabrasf_br_com_ginfes_homologacao_ServiceGinfesImplService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.nfeosasco.com.br/EissnfeWebServices/NotaFiscalEletronica.svc")>  _
        Public ReadOnly Property nfseabrasf_br_com_nfeosasco_www_NotaFiscalEletronicaServico() As String
            Get
                Return CType(Me("nfseabrasf_br_com_nfeosasco_www_NotaFiscalEletronicaServico"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://abrasf.sistemas4r.com.br/arecepcionarloterpssincrono.aspx")>  _
        Public ReadOnly Property nfseabrasf_br_com_sistemas4r_abrasf_nfse_RecepcionarLoteRpsSincrono() As String
            Get
                Return CType(Me("nfseabrasf_br_com_sistemas4r_abrasf_nfse_RecepcionarLoteRpsSincrono"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://abrasf.sistemas4r.com.br/aconsultarnfseporrps.aspx")>  _
        Public ReadOnly Property nfseabrasf_br_com_sistemas4r_abrasf_nfse1_ConsultarNfsePorRps() As String
            Get
                Return CType(Me("nfseabrasf_br_com_sistemas4r_abrasf_nfse1_ConsultarNfsePorRps"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://abrasf.sistemas4r.com.br/acancelarnfse.aspx")>  _
        Public ReadOnly Property nfseabrasf_br_com_sistemas4r_abrasf_nfse4_CancelarNfse() As String
            Get
                Return CType(Me("nfseabrasf_br_com_sistemas4r_abrasf_nfse4_CancelarNfse"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://tatui.sistemas4r.com.br/abrasf/arecepcionarloterpssincrono.aspx")>  _
        Public ReadOnly Property nfseabrasf_br_com_sistemas4r_tatui_nfse_RecepcionarLoteRpsSincrono() As String
            Get
                Return CType(Me("nfseabrasf_br_com_sistemas4r_tatui_nfse_RecepcionarLoteRpsSincrono"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://tatui.sistemas4r.com.br/abrasf/aconsultarnfseporrps.aspx")>  _
        Public ReadOnly Property nfseabrasf_br_com_sistemas4r_tatui_nfse2_ConsultarNfsePorRps() As String
            Get
                Return CType(Me("nfseabrasf_br_com_sistemas4r_tatui_nfse2_ConsultarNfsePorRps"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://tatui.sistemas4r.com.br/abrasf/acancelarnfse.aspx")>  _
        Public ReadOnly Property nfseabrasf_br_com_sistemas4r_tatui_nfse4_CancelarNfse() As String
            Get
                Return CType(Me("nfseabrasf_br_com_sistemas4r_tatui_nfse4_CancelarNfse"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.nfseabrasf.My.MySettings
            Get
                Return Global.nfseabrasf.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
