'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NotaCariocaProducao
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://notacarioca.rio.gov.br/", ConfigurationName:="NotaCariocaProducao.NfseSoap")>  _
    Public Interface NfseSoap
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarNfseRequest) of message ConsultarNfseRequest does not match the default value (ConsultarNfse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/ConsultarNfse", ReplyAction:="*")>  _
        Function ConsultarNfse(ByVal request As NotaCariocaProducao.ConsultarNfseRequest) As NotaCariocaProducao.ConsultarNfseResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarNfsePorRpsRequest) of message ConsultarNfsePorRpsRequest does not match the default value (ConsultarNfsePorRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/ConsultarNfsePorRps", ReplyAction:="*")>  _
        Function ConsultarNfsePorRps(ByVal request As NotaCariocaProducao.ConsultarNfsePorRpsRequest) As NotaCariocaProducao.ConsultarNfsePorRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarLoteRpsRequest) of message ConsultarLoteRpsRequest does not match the default value (ConsultarLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/ConsultarLoteRps", ReplyAction:="*")>  _
        Function ConsultarLoteRps(ByVal request As NotaCariocaProducao.ConsultarLoteRpsRequest) As NotaCariocaProducao.ConsultarLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarSituacaoLoteRpsRequest) of message ConsultarSituacaoLoteRpsRequest does not match the default value (ConsultarSituacaoLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/ConsultarSituacaoLoteRps", ReplyAction:="*")>  _
        Function ConsultarSituacaoLoteRps(ByVal request As NotaCariocaProducao.ConsultarSituacaoLoteRpsRequest) As NotaCariocaProducao.ConsultarSituacaoLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (RecepcionarLoteRpsRequest) of message RecepcionarLoteRpsRequest does not match the default value (RecepcionarLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/RecepcionarLoteRps", ReplyAction:="*")>  _
        Function RecepcionarLoteRps(ByVal request As NotaCariocaProducao.RecepcionarLoteRpsRequest) As NotaCariocaProducao.RecepcionarLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (CancelarNfseRequest) of message CancelarNfseRequest does not match the default value (CancelarNfse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/CancelarNfse", ReplyAction:="*")>  _
        Function CancelarNfse(ByVal request As NotaCariocaProducao.CancelarNfseRequest) As NotaCariocaProducao.CancelarNfseResponse
        
        'CODEGEN: Generating message contract since the wrapper name (GerarNfseRequest) of message GerarNfseRequest does not match the default value (GerarNfse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/GerarNfse", ReplyAction:="*")>  _
        Function GerarNfse(ByVal request As NotaCariocaProducao.GerarNfseRequest) As NotaCariocaProducao.GerarNfseResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfseRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfseResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorRpsRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorRpsResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarLoteRpsRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarLoteRpsResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarSituacaoLoteRpsRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarSituacaoLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarSituacaoLoteRpsResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarSituacaoLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecepcionarLoteRpsRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class RecepcionarLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecepcionarLoteRpsResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class RecepcionarLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelarNfseRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class CancelarNfseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelarNfseResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class CancelarNfseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GerarNfseRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class GerarNfseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GerarNfseResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class GerarNfseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface NfseSoapChannel
        Inherits NotaCariocaProducao.NfseSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class NfseSoapClient
        Inherits System.ServiceModel.ClientBase(Of NotaCariocaProducao.NfseSoap)
        Implements NotaCariocaProducao.NfseSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducao_NfseSoap_ConsultarNfse(ByVal request As NotaCariocaProducao.ConsultarNfseRequest) As NotaCariocaProducao.ConsultarNfseResponse Implements NotaCariocaProducao.NfseSoap.ConsultarNfse
            Return MyBase.Channel.ConsultarNfse(request)
        End Function
        
        Public Function ConsultarNfse(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaProducao.ConsultarNfseRequest = New NotaCariocaProducao.ConsultarNfseRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaProducao.ConsultarNfseResponse = CType(Me,NotaCariocaProducao.NfseSoap).ConsultarNfse(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducao_NfseSoap_ConsultarNfsePorRps(ByVal request As NotaCariocaProducao.ConsultarNfsePorRpsRequest) As NotaCariocaProducao.ConsultarNfsePorRpsResponse Implements NotaCariocaProducao.NfseSoap.ConsultarNfsePorRps
            Return MyBase.Channel.ConsultarNfsePorRps(request)
        End Function
        
        Public Function ConsultarNfsePorRps(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaProducao.ConsultarNfsePorRpsRequest = New NotaCariocaProducao.ConsultarNfsePorRpsRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaProducao.ConsultarNfsePorRpsResponse = CType(Me,NotaCariocaProducao.NfseSoap).ConsultarNfsePorRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducao_NfseSoap_ConsultarLoteRps(ByVal request As NotaCariocaProducao.ConsultarLoteRpsRequest) As NotaCariocaProducao.ConsultarLoteRpsResponse Implements NotaCariocaProducao.NfseSoap.ConsultarLoteRps
            Return MyBase.Channel.ConsultarLoteRps(request)
        End Function
        
        Public Function ConsultarLoteRps(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaProducao.ConsultarLoteRpsRequest = New NotaCariocaProducao.ConsultarLoteRpsRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaProducao.ConsultarLoteRpsResponse = CType(Me,NotaCariocaProducao.NfseSoap).ConsultarLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducao_NfseSoap_ConsultarSituacaoLoteRps(ByVal request As NotaCariocaProducao.ConsultarSituacaoLoteRpsRequest) As NotaCariocaProducao.ConsultarSituacaoLoteRpsResponse Implements NotaCariocaProducao.NfseSoap.ConsultarSituacaoLoteRps
            Return MyBase.Channel.ConsultarSituacaoLoteRps(request)
        End Function
        
        Public Function ConsultarSituacaoLoteRps(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaProducao.ConsultarSituacaoLoteRpsRequest = New NotaCariocaProducao.ConsultarSituacaoLoteRpsRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaProducao.ConsultarSituacaoLoteRpsResponse = CType(Me,NotaCariocaProducao.NfseSoap).ConsultarSituacaoLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducao_NfseSoap_RecepcionarLoteRps(ByVal request As NotaCariocaProducao.RecepcionarLoteRpsRequest) As NotaCariocaProducao.RecepcionarLoteRpsResponse Implements NotaCariocaProducao.NfseSoap.RecepcionarLoteRps
            Return MyBase.Channel.RecepcionarLoteRps(request)
        End Function
        
        Public Function RecepcionarLoteRps(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaProducao.RecepcionarLoteRpsRequest = New NotaCariocaProducao.RecepcionarLoteRpsRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaProducao.RecepcionarLoteRpsResponse = CType(Me,NotaCariocaProducao.NfseSoap).RecepcionarLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducao_NfseSoap_CancelarNfse(ByVal request As NotaCariocaProducao.CancelarNfseRequest) As NotaCariocaProducao.CancelarNfseResponse Implements NotaCariocaProducao.NfseSoap.CancelarNfse
            Return MyBase.Channel.CancelarNfse(request)
        End Function
        
        Public Function CancelarNfse(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaProducao.CancelarNfseRequest = New NotaCariocaProducao.CancelarNfseRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaProducao.CancelarNfseResponse = CType(Me,NotaCariocaProducao.NfseSoap).CancelarNfse(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducao_NfseSoap_GerarNfse(ByVal request As NotaCariocaProducao.GerarNfseRequest) As NotaCariocaProducao.GerarNfseResponse Implements NotaCariocaProducao.NfseSoap.GerarNfse
            Return MyBase.Channel.GerarNfse(request)
        End Function
        
        Public Function GerarNfse(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaProducao.GerarNfseRequest = New NotaCariocaProducao.GerarNfseRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaProducao.GerarNfseResponse = CType(Me,NotaCariocaProducao.NfseSoap).GerarNfse(inValue)
            Return retVal.outputXML
        End Function
    End Class
End Namespace
