'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NotaCariocaHomologacao
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://notacarioca.rio.gov.br/", ConfigurationName:="NotaCariocaHomologacao.NfseSoap")>  _
    Public Interface NfseSoap
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarNfseRequest) of message ConsultarNfseRequest does not match the default value (ConsultarNfse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/ConsultarNfse", ReplyAction:="*")>  _
        Function ConsultarNfse(ByVal request As NotaCariocaHomologacao.ConsultarNfseRequest) As NotaCariocaHomologacao.ConsultarNfseResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarNfsePorRpsRequest) of message ConsultarNfsePorRpsRequest does not match the default value (ConsultarNfsePorRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/ConsultarNfsePorRps", ReplyAction:="*")>  _
        Function ConsultarNfsePorRps(ByVal request As NotaCariocaHomologacao.ConsultarNfsePorRpsRequest) As NotaCariocaHomologacao.ConsultarNfsePorRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarLoteRpsRequest) of message ConsultarLoteRpsRequest does not match the default value (ConsultarLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/ConsultarLoteRps", ReplyAction:="*")>  _
        Function ConsultarLoteRps(ByVal request As NotaCariocaHomologacao.ConsultarLoteRpsRequest) As NotaCariocaHomologacao.ConsultarLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarSituacaoLoteRpsRequest) of message ConsultarSituacaoLoteRpsRequest does not match the default value (ConsultarSituacaoLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/ConsultarSituacaoLoteRps", ReplyAction:="*")>  _
        Function ConsultarSituacaoLoteRps(ByVal request As NotaCariocaHomologacao.ConsultarSituacaoLoteRpsRequest) As NotaCariocaHomologacao.ConsultarSituacaoLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (RecepcionarLoteRpsRequest) of message RecepcionarLoteRpsRequest does not match the default value (RecepcionarLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/RecepcionarLoteRps", ReplyAction:="*")>  _
        Function RecepcionarLoteRps(ByVal request As NotaCariocaHomologacao.RecepcionarLoteRpsRequest) As NotaCariocaHomologacao.RecepcionarLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (CancelarNfseRequest) of message CancelarNfseRequest does not match the default value (CancelarNfse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/CancelarNfse", ReplyAction:="*")>  _
        Function CancelarNfse(ByVal request As NotaCariocaHomologacao.CancelarNfseRequest) As NotaCariocaHomologacao.CancelarNfseResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfseRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfseResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorRpsRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorRpsResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarLoteRpsRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarLoteRpsResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarSituacaoLoteRpsRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarSituacaoLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarSituacaoLoteRpsResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarSituacaoLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecepcionarLoteRpsRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class RecepcionarLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecepcionarLoteRpsResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class RecepcionarLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelarNfseRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class CancelarNfseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelarNfseResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class CancelarNfseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface NfseSoapChannel
        Inherits NotaCariocaHomologacao.NfseSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class NfseSoapClient
        Inherits System.ServiceModel.ClientBase(Of NotaCariocaHomologacao.NfseSoap)
        Implements NotaCariocaHomologacao.NfseSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaHomologacao_NfseSoap_ConsultarNfse(ByVal request As NotaCariocaHomologacao.ConsultarNfseRequest) As NotaCariocaHomologacao.ConsultarNfseResponse Implements NotaCariocaHomologacao.NfseSoap.ConsultarNfse
            Return MyBase.Channel.ConsultarNfse(request)
        End Function
        
        Public Function ConsultarNfse(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaHomologacao.ConsultarNfseRequest = New NotaCariocaHomologacao.ConsultarNfseRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaHomologacao.ConsultarNfseResponse = CType(Me,NotaCariocaHomologacao.NfseSoap).ConsultarNfse(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaHomologacao_NfseSoap_ConsultarNfsePorRps(ByVal request As NotaCariocaHomologacao.ConsultarNfsePorRpsRequest) As NotaCariocaHomologacao.ConsultarNfsePorRpsResponse Implements NotaCariocaHomologacao.NfseSoap.ConsultarNfsePorRps
            Return MyBase.Channel.ConsultarNfsePorRps(request)
        End Function
        
        Public Function ConsultarNfsePorRps(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaHomologacao.ConsultarNfsePorRpsRequest = New NotaCariocaHomologacao.ConsultarNfsePorRpsRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaHomologacao.ConsultarNfsePorRpsResponse = CType(Me,NotaCariocaHomologacao.NfseSoap).ConsultarNfsePorRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaHomologacao_NfseSoap_ConsultarLoteRps(ByVal request As NotaCariocaHomologacao.ConsultarLoteRpsRequest) As NotaCariocaHomologacao.ConsultarLoteRpsResponse Implements NotaCariocaHomologacao.NfseSoap.ConsultarLoteRps
            Return MyBase.Channel.ConsultarLoteRps(request)
        End Function
        
        Public Function ConsultarLoteRps(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaHomologacao.ConsultarLoteRpsRequest = New NotaCariocaHomologacao.ConsultarLoteRpsRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaHomologacao.ConsultarLoteRpsResponse = CType(Me,NotaCariocaHomologacao.NfseSoap).ConsultarLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaHomologacao_NfseSoap_ConsultarSituacaoLoteRps(ByVal request As NotaCariocaHomologacao.ConsultarSituacaoLoteRpsRequest) As NotaCariocaHomologacao.ConsultarSituacaoLoteRpsResponse Implements NotaCariocaHomologacao.NfseSoap.ConsultarSituacaoLoteRps
            Return MyBase.Channel.ConsultarSituacaoLoteRps(request)
        End Function
        
        Public Function ConsultarSituacaoLoteRps(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaHomologacao.ConsultarSituacaoLoteRpsRequest = New NotaCariocaHomologacao.ConsultarSituacaoLoteRpsRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaHomologacao.ConsultarSituacaoLoteRpsResponse = CType(Me,NotaCariocaHomologacao.NfseSoap).ConsultarSituacaoLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaHomologacao_NfseSoap_RecepcionarLoteRps(ByVal request As NotaCariocaHomologacao.RecepcionarLoteRpsRequest) As NotaCariocaHomologacao.RecepcionarLoteRpsResponse Implements NotaCariocaHomologacao.NfseSoap.RecepcionarLoteRps
            Return MyBase.Channel.RecepcionarLoteRps(request)
        End Function
        
        Public Function RecepcionarLoteRps(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaHomologacao.RecepcionarLoteRpsRequest = New NotaCariocaHomologacao.RecepcionarLoteRpsRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaHomologacao.RecepcionarLoteRpsResponse = CType(Me,NotaCariocaHomologacao.NfseSoap).RecepcionarLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaHomologacao_NfseSoap_CancelarNfse(ByVal request As NotaCariocaHomologacao.CancelarNfseRequest) As NotaCariocaHomologacao.CancelarNfseResponse Implements NotaCariocaHomologacao.NfseSoap.CancelarNfse
            Return MyBase.Channel.CancelarNfse(request)
        End Function
        
        Public Function CancelarNfse(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaHomologacao.CancelarNfseRequest = New NotaCariocaHomologacao.CancelarNfseRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaHomologacao.CancelarNfseResponse = CType(Me,NotaCariocaHomologacao.NfseSoap).CancelarNfse(inValue)
            Return retVal.outputXML
        End Function
    End Class
End Namespace
