'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NotaBHHomologacaoAssinc
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ws.bhiss.pbh.gov.br", ConfigurationName:="NotaBHHomologacaoAssinc.nfse")>  _
    Public Interface nfse
        
        'CODEGEN: Generating message contract since the wrapper name (CancelarNfseRequest) of message CancelarNfseRequest does not match the default value (CancelarNfse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/CancelarNfse", ReplyAction:="*")>  _
        Function CancelarNfse(ByVal request As NotaBHHomologacaoAssinc.CancelarNfseRequest) As NotaBHHomologacaoAssinc.CancelarNfseResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://ws.bhiss.pbh.gov.br/CancelarNfse", ReplyAction:="*")>  _
        Function BeginCancelarNfse(ByVal request As NotaBHHomologacaoAssinc.CancelarNfseRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndCancelarNfse(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.CancelarNfseResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarLoteRpsRequest) of message ConsultarLoteRpsRequest does not match the default value (ConsultarLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/ConsultarLoteRps", ReplyAction:="*")>  _
        Function ConsultarLoteRps(ByVal request As NotaBHHomologacaoAssinc.ConsultarLoteRpsRequest) As NotaBHHomologacaoAssinc.ConsultarLoteRpsResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://ws.bhiss.pbh.gov.br/ConsultarLoteRps", ReplyAction:="*")>  _
        Function BeginConsultarLoteRps(ByVal request As NotaBHHomologacaoAssinc.ConsultarLoteRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndConsultarLoteRps(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.ConsultarLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarNfseRequest) of message ConsultarNfseRequest does not match the default value (ConsultarNfse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/ConsultarNfse", ReplyAction:="*")>  _
        Function ConsultarNfse(ByVal request As NotaBHHomologacaoAssinc.ConsultarNfseRequest) As NotaBHHomologacaoAssinc.ConsultarNfseResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://ws.bhiss.pbh.gov.br/ConsultarNfse", ReplyAction:="*")>  _
        Function BeginConsultarNfse(ByVal request As NotaBHHomologacaoAssinc.ConsultarNfseRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndConsultarNfse(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.ConsultarNfseResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarNfsePorFaixaRequest) of message ConsultarNfsePorFaixaRequest does not match the default value (ConsultarNfsePorFaixa)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/ConsultarNfsePorFaixa", ReplyAction:="*")>  _
        Function ConsultarNfsePorFaixa(ByVal request As NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaRequest) As NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://ws.bhiss.pbh.gov.br/ConsultarNfsePorFaixa", ReplyAction:="*")>  _
        Function BeginConsultarNfsePorFaixa(ByVal request As NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndConsultarNfsePorFaixa(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarNfsePorRpsRequest) of message ConsultarNfsePorRpsRequest does not match the default value (ConsultarNfsePorRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/ConsultarNfsePorRps", ReplyAction:="*")>  _
        Function ConsultarNfsePorRps(ByVal request As NotaBHHomologacaoAssinc.ConsultarNfsePorRpsRequest) As NotaBHHomologacaoAssinc.ConsultarNfsePorRpsResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://ws.bhiss.pbh.gov.br/ConsultarNfsePorRps", ReplyAction:="*")>  _
        Function BeginConsultarNfsePorRps(ByVal request As NotaBHHomologacaoAssinc.ConsultarNfsePorRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndConsultarNfsePorRps(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.ConsultarNfsePorRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarSituacaoLoteRpsRequest) of message ConsultarSituacaoLoteRpsRequest does not match the default value (ConsultarSituacaoLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/ConsultarSituacaoLoteRps", ReplyAction:="*")>  _
        Function ConsultarSituacaoLoteRps(ByVal request As NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsRequest) As NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://ws.bhiss.pbh.gov.br/ConsultarSituacaoLoteRps", ReplyAction:="*")>  _
        Function BeginConsultarSituacaoLoteRps(ByVal request As NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndConsultarSituacaoLoteRps(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (RecepcionarLoteRpsRequest) of message RecepcionarLoteRpsRequest does not match the default value (RecepcionarLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/RecepcionarLoteRps", ReplyAction:="*")>  _
        Function RecepcionarLoteRps(ByVal request As NotaBHHomologacaoAssinc.RecepcionarLoteRpsRequest) As NotaBHHomologacaoAssinc.RecepcionarLoteRpsResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://ws.bhiss.pbh.gov.br/RecepcionarLoteRps", ReplyAction:="*")>  _
        Function BeginRecepcionarLoteRps(ByVal request As NotaBHHomologacaoAssinc.RecepcionarLoteRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndRecepcionarLoteRps(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.RecepcionarLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (GerarNfseRequest) of message GerarNfseRequest does not match the default value (GerarNfse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.bhiss.pbh.gov.br/GerarNfse", ReplyAction:="*")>  _
        Function GerarNfse(ByVal request As NotaBHHomologacaoAssinc.GerarNfseRequest) As NotaBHHomologacaoAssinc.GerarNfseResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://ws.bhiss.pbh.gov.br/GerarNfse", ReplyAction:="*")>  _
        Function BeginGerarNfse(ByVal request As NotaBHHomologacaoAssinc.GerarNfseRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGerarNfse(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.GerarNfseResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelarNfseRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class CancelarNfseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelarNfseResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class CancelarNfseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarLoteRpsRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarLoteRpsResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfseRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfseResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorFaixaRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorFaixaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorFaixaResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorFaixaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorRpsRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorRpsResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarSituacaoLoteRpsRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarSituacaoLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarSituacaoLoteRpsResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class ConsultarSituacaoLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecepcionarLoteRpsRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class RecepcionarLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecepcionarLoteRpsResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class RecepcionarLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GerarNfseRequest", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class GerarNfseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public nfseCabecMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public nfseDadosMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            MyBase.New
            Me.nfseCabecMsg = nfseCabecMsg
            Me.nfseDadosMsg = nfseDadosMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GerarNfseResponse", WrapperNamespace:="http://ws.bhiss.pbh.gov.br", IsWrapped:=true)>  _
    Partial Public Class GerarNfseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface nfseChannel
        Inherits NotaBHHomologacaoAssinc.nfse, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CancelarNfseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ConsultarLoteRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ConsultarNfseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ConsultarNfsePorFaixaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ConsultarNfsePorRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ConsultarSituacaoLoteRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RecepcionarLoteRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GerarNfseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class nfseClient
        Inherits System.ServiceModel.ClientBase(Of NotaBHHomologacaoAssinc.nfse)
        Implements NotaBHHomologacaoAssinc.nfse
        
        Private onBeginCancelarNfseDelegate As BeginOperationDelegate
        
        Private onEndCancelarNfseDelegate As EndOperationDelegate
        
        Private onCancelarNfseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginConsultarLoteRpsDelegate As BeginOperationDelegate
        
        Private onEndConsultarLoteRpsDelegate As EndOperationDelegate
        
        Private onConsultarLoteRpsCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginConsultarNfseDelegate As BeginOperationDelegate
        
        Private onEndConsultarNfseDelegate As EndOperationDelegate
        
        Private onConsultarNfseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginConsultarNfsePorFaixaDelegate As BeginOperationDelegate
        
        Private onEndConsultarNfsePorFaixaDelegate As EndOperationDelegate
        
        Private onConsultarNfsePorFaixaCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginConsultarNfsePorRpsDelegate As BeginOperationDelegate
        
        Private onEndConsultarNfsePorRpsDelegate As EndOperationDelegate
        
        Private onConsultarNfsePorRpsCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginConsultarSituacaoLoteRpsDelegate As BeginOperationDelegate
        
        Private onEndConsultarSituacaoLoteRpsDelegate As EndOperationDelegate
        
        Private onConsultarSituacaoLoteRpsCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginRecepcionarLoteRpsDelegate As BeginOperationDelegate
        
        Private onEndRecepcionarLoteRpsDelegate As EndOperationDelegate
        
        Private onRecepcionarLoteRpsCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginGerarNfseDelegate As BeginOperationDelegate
        
        Private onEndGerarNfseDelegate As EndOperationDelegate
        
        Private onGerarNfseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event CancelarNfseCompleted As System.EventHandler(Of CancelarNfseCompletedEventArgs)
        
        Public Event ConsultarLoteRpsCompleted As System.EventHandler(Of ConsultarLoteRpsCompletedEventArgs)
        
        Public Event ConsultarNfseCompleted As System.EventHandler(Of ConsultarNfseCompletedEventArgs)
        
        Public Event ConsultarNfsePorFaixaCompleted As System.EventHandler(Of ConsultarNfsePorFaixaCompletedEventArgs)
        
        Public Event ConsultarNfsePorRpsCompleted As System.EventHandler(Of ConsultarNfsePorRpsCompletedEventArgs)
        
        Public Event ConsultarSituacaoLoteRpsCompleted As System.EventHandler(Of ConsultarSituacaoLoteRpsCompletedEventArgs)
        
        Public Event RecepcionarLoteRpsCompleted As System.EventHandler(Of RecepcionarLoteRpsCompletedEventArgs)
        
        Public Event GerarNfseCompleted As System.EventHandler(Of GerarNfseCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_CancelarNfse(ByVal request As NotaBHHomologacaoAssinc.CancelarNfseRequest) As NotaBHHomologacaoAssinc.CancelarNfseResponse Implements NotaBHHomologacaoAssinc.nfse.CancelarNfse
            Return MyBase.Channel.CancelarNfse(request)
        End Function
        
        Public Function CancelarNfse(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As NotaBHHomologacaoAssinc.CancelarNfseRequest = New NotaBHHomologacaoAssinc.CancelarNfseRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As NotaBHHomologacaoAssinc.CancelarNfseResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).CancelarNfse(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_BeginCancelarNfse(ByVal request As NotaBHHomologacaoAssinc.CancelarNfseRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaBHHomologacaoAssinc.nfse.BeginCancelarNfse
            Return MyBase.Channel.BeginCancelarNfse(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginCancelarNfse(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaBHHomologacaoAssinc.CancelarNfseRequest = New NotaBHHomologacaoAssinc.CancelarNfseRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Return CType(Me,NotaBHHomologacaoAssinc.nfse).BeginCancelarNfse(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_EndCancelarNfse(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.CancelarNfseResponse Implements NotaBHHomologacaoAssinc.nfse.EndCancelarNfse
            Return MyBase.Channel.EndCancelarNfse(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndCancelarNfse(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaBHHomologacaoAssinc.CancelarNfseResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).EndCancelarNfse(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginCancelarNfse(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim nfseCabecMsg As String = CType(inValues(0),String)
            Dim nfseDadosMsg As String = CType(inValues(1),String)
            Return Me.BeginCancelarNfse(nfseCabecMsg, nfseDadosMsg, callback, asyncState)
        End Function
        
        Private Function OnEndCancelarNfse(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndCancelarNfse(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnCancelarNfseCompleted(ByVal state As Object)
            If (Not (Me.CancelarNfseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CancelarNfseCompleted(Me, New CancelarNfseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CancelarNfseAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            Me.CancelarNfseAsync(nfseCabecMsg, nfseDadosMsg, Nothing)
        End Sub
        
        Public Overloads Sub CancelarNfseAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal userState As Object)
            If (Me.onBeginCancelarNfseDelegate Is Nothing) Then
                Me.onBeginCancelarNfseDelegate = AddressOf Me.OnBeginCancelarNfse
            End If
            If (Me.onEndCancelarNfseDelegate Is Nothing) Then
                Me.onEndCancelarNfseDelegate = AddressOf Me.OnEndCancelarNfse
            End If
            If (Me.onCancelarNfseCompletedDelegate Is Nothing) Then
                Me.onCancelarNfseCompletedDelegate = AddressOf Me.OnCancelarNfseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCancelarNfseDelegate, New Object() {nfseCabecMsg, nfseDadosMsg}, Me.onEndCancelarNfseDelegate, Me.onCancelarNfseCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_ConsultarLoteRps(ByVal request As NotaBHHomologacaoAssinc.ConsultarLoteRpsRequest) As NotaBHHomologacaoAssinc.ConsultarLoteRpsResponse Implements NotaBHHomologacaoAssinc.nfse.ConsultarLoteRps
            Return MyBase.Channel.ConsultarLoteRps(request)
        End Function
        
        Public Function ConsultarLoteRps(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As NotaBHHomologacaoAssinc.ConsultarLoteRpsRequest = New NotaBHHomologacaoAssinc.ConsultarLoteRpsRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As NotaBHHomologacaoAssinc.ConsultarLoteRpsResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).ConsultarLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_BeginConsultarLoteRps(ByVal request As NotaBHHomologacaoAssinc.ConsultarLoteRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaBHHomologacaoAssinc.nfse.BeginConsultarLoteRps
            Return MyBase.Channel.BeginConsultarLoteRps(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginConsultarLoteRps(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaBHHomologacaoAssinc.ConsultarLoteRpsRequest = New NotaBHHomologacaoAssinc.ConsultarLoteRpsRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Return CType(Me,NotaBHHomologacaoAssinc.nfse).BeginConsultarLoteRps(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_EndConsultarLoteRps(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.ConsultarLoteRpsResponse Implements NotaBHHomologacaoAssinc.nfse.EndConsultarLoteRps
            Return MyBase.Channel.EndConsultarLoteRps(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndConsultarLoteRps(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaBHHomologacaoAssinc.ConsultarLoteRpsResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).EndConsultarLoteRps(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginConsultarLoteRps(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim nfseCabecMsg As String = CType(inValues(0),String)
            Dim nfseDadosMsg As String = CType(inValues(1),String)
            Return Me.BeginConsultarLoteRps(nfseCabecMsg, nfseDadosMsg, callback, asyncState)
        End Function
        
        Private Function OnEndConsultarLoteRps(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndConsultarLoteRps(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnConsultarLoteRpsCompleted(ByVal state As Object)
            If (Not (Me.ConsultarLoteRpsCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ConsultarLoteRpsCompleted(Me, New ConsultarLoteRpsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ConsultarLoteRpsAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            Me.ConsultarLoteRpsAsync(nfseCabecMsg, nfseDadosMsg, Nothing)
        End Sub
        
        Public Overloads Sub ConsultarLoteRpsAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal userState As Object)
            If (Me.onBeginConsultarLoteRpsDelegate Is Nothing) Then
                Me.onBeginConsultarLoteRpsDelegate = AddressOf Me.OnBeginConsultarLoteRps
            End If
            If (Me.onEndConsultarLoteRpsDelegate Is Nothing) Then
                Me.onEndConsultarLoteRpsDelegate = AddressOf Me.OnEndConsultarLoteRps
            End If
            If (Me.onConsultarLoteRpsCompletedDelegate Is Nothing) Then
                Me.onConsultarLoteRpsCompletedDelegate = AddressOf Me.OnConsultarLoteRpsCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginConsultarLoteRpsDelegate, New Object() {nfseCabecMsg, nfseDadosMsg}, Me.onEndConsultarLoteRpsDelegate, Me.onConsultarLoteRpsCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_ConsultarNfse(ByVal request As NotaBHHomologacaoAssinc.ConsultarNfseRequest) As NotaBHHomologacaoAssinc.ConsultarNfseResponse Implements NotaBHHomologacaoAssinc.nfse.ConsultarNfse
            Return MyBase.Channel.ConsultarNfse(request)
        End Function
        
        Public Function ConsultarNfse(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As NotaBHHomologacaoAssinc.ConsultarNfseRequest = New NotaBHHomologacaoAssinc.ConsultarNfseRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As NotaBHHomologacaoAssinc.ConsultarNfseResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).ConsultarNfse(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_BeginConsultarNfse(ByVal request As NotaBHHomologacaoAssinc.ConsultarNfseRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaBHHomologacaoAssinc.nfse.BeginConsultarNfse
            Return MyBase.Channel.BeginConsultarNfse(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginConsultarNfse(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaBHHomologacaoAssinc.ConsultarNfseRequest = New NotaBHHomologacaoAssinc.ConsultarNfseRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Return CType(Me,NotaBHHomologacaoAssinc.nfse).BeginConsultarNfse(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_EndConsultarNfse(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.ConsultarNfseResponse Implements NotaBHHomologacaoAssinc.nfse.EndConsultarNfse
            Return MyBase.Channel.EndConsultarNfse(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndConsultarNfse(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaBHHomologacaoAssinc.ConsultarNfseResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).EndConsultarNfse(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginConsultarNfse(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim nfseCabecMsg As String = CType(inValues(0),String)
            Dim nfseDadosMsg As String = CType(inValues(1),String)
            Return Me.BeginConsultarNfse(nfseCabecMsg, nfseDadosMsg, callback, asyncState)
        End Function
        
        Private Function OnEndConsultarNfse(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndConsultarNfse(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnConsultarNfseCompleted(ByVal state As Object)
            If (Not (Me.ConsultarNfseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ConsultarNfseCompleted(Me, New ConsultarNfseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ConsultarNfseAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            Me.ConsultarNfseAsync(nfseCabecMsg, nfseDadosMsg, Nothing)
        End Sub
        
        Public Overloads Sub ConsultarNfseAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal userState As Object)
            If (Me.onBeginConsultarNfseDelegate Is Nothing) Then
                Me.onBeginConsultarNfseDelegate = AddressOf Me.OnBeginConsultarNfse
            End If
            If (Me.onEndConsultarNfseDelegate Is Nothing) Then
                Me.onEndConsultarNfseDelegate = AddressOf Me.OnEndConsultarNfse
            End If
            If (Me.onConsultarNfseCompletedDelegate Is Nothing) Then
                Me.onConsultarNfseCompletedDelegate = AddressOf Me.OnConsultarNfseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginConsultarNfseDelegate, New Object() {nfseCabecMsg, nfseDadosMsg}, Me.onEndConsultarNfseDelegate, Me.onConsultarNfseCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_ConsultarNfsePorFaixa(ByVal request As NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaRequest) As NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaResponse Implements NotaBHHomologacaoAssinc.nfse.ConsultarNfsePorFaixa
            Return MyBase.Channel.ConsultarNfsePorFaixa(request)
        End Function
        
        Public Function ConsultarNfsePorFaixa(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaRequest = New NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).ConsultarNfsePorFaixa(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_BeginConsultarNfsePorFaixa(ByVal request As NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaBHHomologacaoAssinc.nfse.BeginConsultarNfsePorFaixa
            Return MyBase.Channel.BeginConsultarNfsePorFaixa(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginConsultarNfsePorFaixa(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaRequest = New NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Return CType(Me,NotaBHHomologacaoAssinc.nfse).BeginConsultarNfsePorFaixa(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_EndConsultarNfsePorFaixa(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaResponse Implements NotaBHHomologacaoAssinc.nfse.EndConsultarNfsePorFaixa
            Return MyBase.Channel.EndConsultarNfsePorFaixa(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndConsultarNfsePorFaixa(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaBHHomologacaoAssinc.ConsultarNfsePorFaixaResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).EndConsultarNfsePorFaixa(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginConsultarNfsePorFaixa(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim nfseCabecMsg As String = CType(inValues(0),String)
            Dim nfseDadosMsg As String = CType(inValues(1),String)
            Return Me.BeginConsultarNfsePorFaixa(nfseCabecMsg, nfseDadosMsg, callback, asyncState)
        End Function
        
        Private Function OnEndConsultarNfsePorFaixa(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndConsultarNfsePorFaixa(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnConsultarNfsePorFaixaCompleted(ByVal state As Object)
            If (Not (Me.ConsultarNfsePorFaixaCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ConsultarNfsePorFaixaCompleted(Me, New ConsultarNfsePorFaixaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ConsultarNfsePorFaixaAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            Me.ConsultarNfsePorFaixaAsync(nfseCabecMsg, nfseDadosMsg, Nothing)
        End Sub
        
        Public Overloads Sub ConsultarNfsePorFaixaAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal userState As Object)
            If (Me.onBeginConsultarNfsePorFaixaDelegate Is Nothing) Then
                Me.onBeginConsultarNfsePorFaixaDelegate = AddressOf Me.OnBeginConsultarNfsePorFaixa
            End If
            If (Me.onEndConsultarNfsePorFaixaDelegate Is Nothing) Then
                Me.onEndConsultarNfsePorFaixaDelegate = AddressOf Me.OnEndConsultarNfsePorFaixa
            End If
            If (Me.onConsultarNfsePorFaixaCompletedDelegate Is Nothing) Then
                Me.onConsultarNfsePorFaixaCompletedDelegate = AddressOf Me.OnConsultarNfsePorFaixaCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginConsultarNfsePorFaixaDelegate, New Object() {nfseCabecMsg, nfseDadosMsg}, Me.onEndConsultarNfsePorFaixaDelegate, Me.onConsultarNfsePorFaixaCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_ConsultarNfsePorRps(ByVal request As NotaBHHomologacaoAssinc.ConsultarNfsePorRpsRequest) As NotaBHHomologacaoAssinc.ConsultarNfsePorRpsResponse Implements NotaBHHomologacaoAssinc.nfse.ConsultarNfsePorRps
            Return MyBase.Channel.ConsultarNfsePorRps(request)
        End Function
        
        Public Function ConsultarNfsePorRps(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As NotaBHHomologacaoAssinc.ConsultarNfsePorRpsRequest = New NotaBHHomologacaoAssinc.ConsultarNfsePorRpsRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As NotaBHHomologacaoAssinc.ConsultarNfsePorRpsResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).ConsultarNfsePorRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_BeginConsultarNfsePorRps(ByVal request As NotaBHHomologacaoAssinc.ConsultarNfsePorRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaBHHomologacaoAssinc.nfse.BeginConsultarNfsePorRps
            Return MyBase.Channel.BeginConsultarNfsePorRps(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginConsultarNfsePorRps(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaBHHomologacaoAssinc.ConsultarNfsePorRpsRequest = New NotaBHHomologacaoAssinc.ConsultarNfsePorRpsRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Return CType(Me,NotaBHHomologacaoAssinc.nfse).BeginConsultarNfsePorRps(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_EndConsultarNfsePorRps(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.ConsultarNfsePorRpsResponse Implements NotaBHHomologacaoAssinc.nfse.EndConsultarNfsePorRps
            Return MyBase.Channel.EndConsultarNfsePorRps(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndConsultarNfsePorRps(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaBHHomologacaoAssinc.ConsultarNfsePorRpsResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).EndConsultarNfsePorRps(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginConsultarNfsePorRps(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim nfseCabecMsg As String = CType(inValues(0),String)
            Dim nfseDadosMsg As String = CType(inValues(1),String)
            Return Me.BeginConsultarNfsePorRps(nfseCabecMsg, nfseDadosMsg, callback, asyncState)
        End Function
        
        Private Function OnEndConsultarNfsePorRps(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndConsultarNfsePorRps(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnConsultarNfsePorRpsCompleted(ByVal state As Object)
            If (Not (Me.ConsultarNfsePorRpsCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ConsultarNfsePorRpsCompleted(Me, New ConsultarNfsePorRpsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ConsultarNfsePorRpsAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            Me.ConsultarNfsePorRpsAsync(nfseCabecMsg, nfseDadosMsg, Nothing)
        End Sub
        
        Public Overloads Sub ConsultarNfsePorRpsAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal userState As Object)
            If (Me.onBeginConsultarNfsePorRpsDelegate Is Nothing) Then
                Me.onBeginConsultarNfsePorRpsDelegate = AddressOf Me.OnBeginConsultarNfsePorRps
            End If
            If (Me.onEndConsultarNfsePorRpsDelegate Is Nothing) Then
                Me.onEndConsultarNfsePorRpsDelegate = AddressOf Me.OnEndConsultarNfsePorRps
            End If
            If (Me.onConsultarNfsePorRpsCompletedDelegate Is Nothing) Then
                Me.onConsultarNfsePorRpsCompletedDelegate = AddressOf Me.OnConsultarNfsePorRpsCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginConsultarNfsePorRpsDelegate, New Object() {nfseCabecMsg, nfseDadosMsg}, Me.onEndConsultarNfsePorRpsDelegate, Me.onConsultarNfsePorRpsCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_ConsultarSituacaoLoteRps(ByVal request As NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsRequest) As NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsResponse Implements NotaBHHomologacaoAssinc.nfse.ConsultarSituacaoLoteRps
            Return MyBase.Channel.ConsultarSituacaoLoteRps(request)
        End Function
        
        Public Function ConsultarSituacaoLoteRps(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsRequest = New NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).ConsultarSituacaoLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_BeginConsultarSituacaoLoteRps(ByVal request As NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaBHHomologacaoAssinc.nfse.BeginConsultarSituacaoLoteRps
            Return MyBase.Channel.BeginConsultarSituacaoLoteRps(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginConsultarSituacaoLoteRps(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsRequest = New NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Return CType(Me,NotaBHHomologacaoAssinc.nfse).BeginConsultarSituacaoLoteRps(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_EndConsultarSituacaoLoteRps(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsResponse Implements NotaBHHomologacaoAssinc.nfse.EndConsultarSituacaoLoteRps
            Return MyBase.Channel.EndConsultarSituacaoLoteRps(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndConsultarSituacaoLoteRps(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaBHHomologacaoAssinc.ConsultarSituacaoLoteRpsResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).EndConsultarSituacaoLoteRps(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginConsultarSituacaoLoteRps(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim nfseCabecMsg As String = CType(inValues(0),String)
            Dim nfseDadosMsg As String = CType(inValues(1),String)
            Return Me.BeginConsultarSituacaoLoteRps(nfseCabecMsg, nfseDadosMsg, callback, asyncState)
        End Function
        
        Private Function OnEndConsultarSituacaoLoteRps(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndConsultarSituacaoLoteRps(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnConsultarSituacaoLoteRpsCompleted(ByVal state As Object)
            If (Not (Me.ConsultarSituacaoLoteRpsCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ConsultarSituacaoLoteRpsCompleted(Me, New ConsultarSituacaoLoteRpsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ConsultarSituacaoLoteRpsAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            Me.ConsultarSituacaoLoteRpsAsync(nfseCabecMsg, nfseDadosMsg, Nothing)
        End Sub
        
        Public Overloads Sub ConsultarSituacaoLoteRpsAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal userState As Object)
            If (Me.onBeginConsultarSituacaoLoteRpsDelegate Is Nothing) Then
                Me.onBeginConsultarSituacaoLoteRpsDelegate = AddressOf Me.OnBeginConsultarSituacaoLoteRps
            End If
            If (Me.onEndConsultarSituacaoLoteRpsDelegate Is Nothing) Then
                Me.onEndConsultarSituacaoLoteRpsDelegate = AddressOf Me.OnEndConsultarSituacaoLoteRps
            End If
            If (Me.onConsultarSituacaoLoteRpsCompletedDelegate Is Nothing) Then
                Me.onConsultarSituacaoLoteRpsCompletedDelegate = AddressOf Me.OnConsultarSituacaoLoteRpsCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginConsultarSituacaoLoteRpsDelegate, New Object() {nfseCabecMsg, nfseDadosMsg}, Me.onEndConsultarSituacaoLoteRpsDelegate, Me.onConsultarSituacaoLoteRpsCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_RecepcionarLoteRps(ByVal request As NotaBHHomologacaoAssinc.RecepcionarLoteRpsRequest) As NotaBHHomologacaoAssinc.RecepcionarLoteRpsResponse Implements NotaBHHomologacaoAssinc.nfse.RecepcionarLoteRps
            Return MyBase.Channel.RecepcionarLoteRps(request)
        End Function
        
        Public Function RecepcionarLoteRps(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As NotaBHHomologacaoAssinc.RecepcionarLoteRpsRequest = New NotaBHHomologacaoAssinc.RecepcionarLoteRpsRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As NotaBHHomologacaoAssinc.RecepcionarLoteRpsResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).RecepcionarLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_BeginRecepcionarLoteRps(ByVal request As NotaBHHomologacaoAssinc.RecepcionarLoteRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaBHHomologacaoAssinc.nfse.BeginRecepcionarLoteRps
            Return MyBase.Channel.BeginRecepcionarLoteRps(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginRecepcionarLoteRps(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaBHHomologacaoAssinc.RecepcionarLoteRpsRequest = New NotaBHHomologacaoAssinc.RecepcionarLoteRpsRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Return CType(Me,NotaBHHomologacaoAssinc.nfse).BeginRecepcionarLoteRps(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_EndRecepcionarLoteRps(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.RecepcionarLoteRpsResponse Implements NotaBHHomologacaoAssinc.nfse.EndRecepcionarLoteRps
            Return MyBase.Channel.EndRecepcionarLoteRps(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndRecepcionarLoteRps(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaBHHomologacaoAssinc.RecepcionarLoteRpsResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).EndRecepcionarLoteRps(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginRecepcionarLoteRps(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim nfseCabecMsg As String = CType(inValues(0),String)
            Dim nfseDadosMsg As String = CType(inValues(1),String)
            Return Me.BeginRecepcionarLoteRps(nfseCabecMsg, nfseDadosMsg, callback, asyncState)
        End Function
        
        Private Function OnEndRecepcionarLoteRps(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndRecepcionarLoteRps(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnRecepcionarLoteRpsCompleted(ByVal state As Object)
            If (Not (Me.RecepcionarLoteRpsCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent RecepcionarLoteRpsCompleted(Me, New RecepcionarLoteRpsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub RecepcionarLoteRpsAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            Me.RecepcionarLoteRpsAsync(nfseCabecMsg, nfseDadosMsg, Nothing)
        End Sub
        
        Public Overloads Sub RecepcionarLoteRpsAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal userState As Object)
            If (Me.onBeginRecepcionarLoteRpsDelegate Is Nothing) Then
                Me.onBeginRecepcionarLoteRpsDelegate = AddressOf Me.OnBeginRecepcionarLoteRps
            End If
            If (Me.onEndRecepcionarLoteRpsDelegate Is Nothing) Then
                Me.onEndRecepcionarLoteRpsDelegate = AddressOf Me.OnEndRecepcionarLoteRps
            End If
            If (Me.onRecepcionarLoteRpsCompletedDelegate Is Nothing) Then
                Me.onRecepcionarLoteRpsCompletedDelegate = AddressOf Me.OnRecepcionarLoteRpsCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginRecepcionarLoteRpsDelegate, New Object() {nfseCabecMsg, nfseDadosMsg}, Me.onEndRecepcionarLoteRpsDelegate, Me.onRecepcionarLoteRpsCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_GerarNfse(ByVal request As NotaBHHomologacaoAssinc.GerarNfseRequest) As NotaBHHomologacaoAssinc.GerarNfseResponse Implements NotaBHHomologacaoAssinc.nfse.GerarNfse
            Return MyBase.Channel.GerarNfse(request)
        End Function
        
        Public Function GerarNfse(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String) As String
            Dim inValue As NotaBHHomologacaoAssinc.GerarNfseRequest = New NotaBHHomologacaoAssinc.GerarNfseRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Dim retVal As NotaBHHomologacaoAssinc.GerarNfseResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).GerarNfse(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_BeginGerarNfse(ByVal request As NotaBHHomologacaoAssinc.GerarNfseRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaBHHomologacaoAssinc.nfse.BeginGerarNfse
            Return MyBase.Channel.BeginGerarNfse(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginGerarNfse(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaBHHomologacaoAssinc.GerarNfseRequest = New NotaBHHomologacaoAssinc.GerarNfseRequest()
            inValue.nfseCabecMsg = nfseCabecMsg
            inValue.nfseDadosMsg = nfseDadosMsg
            Return CType(Me,NotaBHHomologacaoAssinc.nfse).BeginGerarNfse(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaBHHomologacaoAssinc_nfse_EndGerarNfse(ByVal result As System.IAsyncResult) As NotaBHHomologacaoAssinc.GerarNfseResponse Implements NotaBHHomologacaoAssinc.nfse.EndGerarNfse
            Return MyBase.Channel.EndGerarNfse(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndGerarNfse(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaBHHomologacaoAssinc.GerarNfseResponse = CType(Me,NotaBHHomologacaoAssinc.nfse).EndGerarNfse(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginGerarNfse(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim nfseCabecMsg As String = CType(inValues(0),String)
            Dim nfseDadosMsg As String = CType(inValues(1),String)
            Return Me.BeginGerarNfse(nfseCabecMsg, nfseDadosMsg, callback, asyncState)
        End Function
        
        Private Function OnEndGerarNfse(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndGerarNfse(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnGerarNfseCompleted(ByVal state As Object)
            If (Not (Me.GerarNfseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GerarNfseCompleted(Me, New GerarNfseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GerarNfseAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String)
            Me.GerarNfseAsync(nfseCabecMsg, nfseDadosMsg, Nothing)
        End Sub
        
        Public Overloads Sub GerarNfseAsync(ByVal nfseCabecMsg As String, ByVal nfseDadosMsg As String, ByVal userState As Object)
            If (Me.onBeginGerarNfseDelegate Is Nothing) Then
                Me.onBeginGerarNfseDelegate = AddressOf Me.OnBeginGerarNfse
            End If
            If (Me.onEndGerarNfseDelegate Is Nothing) Then
                Me.onEndGerarNfseDelegate = AddressOf Me.OnEndGerarNfse
            End If
            If (Me.onGerarNfseCompletedDelegate Is Nothing) Then
                Me.onGerarNfseCompletedDelegate = AddressOf Me.OnGerarNfseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGerarNfseDelegate, New Object() {nfseCabecMsg, nfseDadosMsg}, Me.onEndGerarNfseDelegate, Me.onGerarNfseCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
