'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NotaCariocaProducaoAssinc
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://notacarioca.rio.gov.br/", ConfigurationName:="NotaCariocaProducaoAssinc.NfseSoap")>  _
    Public Interface NfseSoap
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarNfseRequest) of message ConsultarNfseRequest does not match the default value (ConsultarNfse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/ConsultarNfse", ReplyAction:="*")>  _
        Function ConsultarNfse(ByVal request As NotaCariocaProducaoAssinc.ConsultarNfseRequest) As NotaCariocaProducaoAssinc.ConsultarNfseResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://notacarioca.rio.gov.br/ConsultarNfse", ReplyAction:="*")>  _
        Function BeginConsultarNfse(ByVal request As NotaCariocaProducaoAssinc.ConsultarNfseRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndConsultarNfse(ByVal result As System.IAsyncResult) As NotaCariocaProducaoAssinc.ConsultarNfseResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarNfsePorRpsRequest) of message ConsultarNfsePorRpsRequest does not match the default value (ConsultarNfsePorRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/ConsultarNfsePorRps", ReplyAction:="*")>  _
        Function ConsultarNfsePorRps(ByVal request As NotaCariocaProducaoAssinc.ConsultarNfsePorRpsRequest) As NotaCariocaProducaoAssinc.ConsultarNfsePorRpsResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://notacarioca.rio.gov.br/ConsultarNfsePorRps", ReplyAction:="*")>  _
        Function BeginConsultarNfsePorRps(ByVal request As NotaCariocaProducaoAssinc.ConsultarNfsePorRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndConsultarNfsePorRps(ByVal result As System.IAsyncResult) As NotaCariocaProducaoAssinc.ConsultarNfsePorRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarLoteRpsRequest) of message ConsultarLoteRpsRequest does not match the default value (ConsultarLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/ConsultarLoteRps", ReplyAction:="*")>  _
        Function ConsultarLoteRps(ByVal request As NotaCariocaProducaoAssinc.ConsultarLoteRpsRequest) As NotaCariocaProducaoAssinc.ConsultarLoteRpsResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://notacarioca.rio.gov.br/ConsultarLoteRps", ReplyAction:="*")>  _
        Function BeginConsultarLoteRps(ByVal request As NotaCariocaProducaoAssinc.ConsultarLoteRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndConsultarLoteRps(ByVal result As System.IAsyncResult) As NotaCariocaProducaoAssinc.ConsultarLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (ConsultarSituacaoLoteRpsRequest) of message ConsultarSituacaoLoteRpsRequest does not match the default value (ConsultarSituacaoLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/ConsultarSituacaoLoteRps", ReplyAction:="*")>  _
        Function ConsultarSituacaoLoteRps(ByVal request As NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsRequest) As NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://notacarioca.rio.gov.br/ConsultarSituacaoLoteRps", ReplyAction:="*")>  _
        Function BeginConsultarSituacaoLoteRps(ByVal request As NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndConsultarSituacaoLoteRps(ByVal result As System.IAsyncResult) As NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (RecepcionarLoteRpsRequest) of message RecepcionarLoteRpsRequest does not match the default value (RecepcionarLoteRps)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/RecepcionarLoteRps", ReplyAction:="*")>  _
        Function RecepcionarLoteRps(ByVal request As NotaCariocaProducaoAssinc.RecepcionarLoteRpsRequest) As NotaCariocaProducaoAssinc.RecepcionarLoteRpsResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://notacarioca.rio.gov.br/RecepcionarLoteRps", ReplyAction:="*")>  _
        Function BeginRecepcionarLoteRps(ByVal request As NotaCariocaProducaoAssinc.RecepcionarLoteRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndRecepcionarLoteRps(ByVal result As System.IAsyncResult) As NotaCariocaProducaoAssinc.RecepcionarLoteRpsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (CancelarNfseRequest) of message CancelarNfseRequest does not match the default value (CancelarNfse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://notacarioca.rio.gov.br/CancelarNfse", ReplyAction:="*")>  _
        Function CancelarNfse(ByVal request As NotaCariocaProducaoAssinc.CancelarNfseRequest) As NotaCariocaProducaoAssinc.CancelarNfseResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://notacarioca.rio.gov.br/CancelarNfse", ReplyAction:="*")>  _
        Function BeginCancelarNfse(ByVal request As NotaCariocaProducaoAssinc.CancelarNfseRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndCancelarNfse(ByVal result As System.IAsyncResult) As NotaCariocaProducaoAssinc.CancelarNfseResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfseRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfseResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorRpsRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarNfsePorRpsResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarNfsePorRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarLoteRpsRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarLoteRpsResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarSituacaoLoteRpsRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarSituacaoLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarSituacaoLoteRpsResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class ConsultarSituacaoLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecepcionarLoteRpsRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class RecepcionarLoteRpsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecepcionarLoteRpsResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class RecepcionarLoteRpsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelarNfseRequest", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class CancelarNfseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public inputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal inputXML As String)
            MyBase.New
            Me.inputXML = inputXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelarNfseResponse", WrapperNamespace:="http://notacarioca.rio.gov.br/", IsWrapped:=true)>  _
    Partial Public Class CancelarNfseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://notacarioca.rio.gov.br/", Order:=0)>  _
        Public outputXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal outputXML As String)
            MyBase.New
            Me.outputXML = outputXML
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface NfseSoapChannel
        Inherits NotaCariocaProducaoAssinc.NfseSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ConsultarNfseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ConsultarNfsePorRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ConsultarLoteRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ConsultarSituacaoLoteRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RecepcionarLoteRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CancelarNfseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class NfseSoapClient
        Inherits System.ServiceModel.ClientBase(Of NotaCariocaProducaoAssinc.NfseSoap)
        Implements NotaCariocaProducaoAssinc.NfseSoap
        
        Private onBeginConsultarNfseDelegate As BeginOperationDelegate
        
        Private onEndConsultarNfseDelegate As EndOperationDelegate
        
        Private onConsultarNfseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginConsultarNfsePorRpsDelegate As BeginOperationDelegate
        
        Private onEndConsultarNfsePorRpsDelegate As EndOperationDelegate
        
        Private onConsultarNfsePorRpsCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginConsultarLoteRpsDelegate As BeginOperationDelegate
        
        Private onEndConsultarLoteRpsDelegate As EndOperationDelegate
        
        Private onConsultarLoteRpsCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginConsultarSituacaoLoteRpsDelegate As BeginOperationDelegate
        
        Private onEndConsultarSituacaoLoteRpsDelegate As EndOperationDelegate
        
        Private onConsultarSituacaoLoteRpsCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginRecepcionarLoteRpsDelegate As BeginOperationDelegate
        
        Private onEndRecepcionarLoteRpsDelegate As EndOperationDelegate
        
        Private onRecepcionarLoteRpsCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginCancelarNfseDelegate As BeginOperationDelegate
        
        Private onEndCancelarNfseDelegate As EndOperationDelegate
        
        Private onCancelarNfseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event ConsultarNfseCompleted As System.EventHandler(Of ConsultarNfseCompletedEventArgs)
        
        Public Event ConsultarNfsePorRpsCompleted As System.EventHandler(Of ConsultarNfsePorRpsCompletedEventArgs)
        
        Public Event ConsultarLoteRpsCompleted As System.EventHandler(Of ConsultarLoteRpsCompletedEventArgs)
        
        Public Event ConsultarSituacaoLoteRpsCompleted As System.EventHandler(Of ConsultarSituacaoLoteRpsCompletedEventArgs)
        
        Public Event RecepcionarLoteRpsCompleted As System.EventHandler(Of RecepcionarLoteRpsCompletedEventArgs)
        
        Public Event CancelarNfseCompleted As System.EventHandler(Of CancelarNfseCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_ConsultarNfse(ByVal request As NotaCariocaProducaoAssinc.ConsultarNfseRequest) As NotaCariocaProducaoAssinc.ConsultarNfseResponse Implements NotaCariocaProducaoAssinc.NfseSoap.ConsultarNfse
            Return MyBase.Channel.ConsultarNfse(request)
        End Function
        
        Public Function ConsultarNfse(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaProducaoAssinc.ConsultarNfseRequest = New NotaCariocaProducaoAssinc.ConsultarNfseRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaProducaoAssinc.ConsultarNfseResponse = CType(Me,NotaCariocaProducaoAssinc.NfseSoap).ConsultarNfse(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_BeginConsultarNfse(ByVal request As NotaCariocaProducaoAssinc.ConsultarNfseRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaCariocaProducaoAssinc.NfseSoap.BeginConsultarNfse
            Return MyBase.Channel.BeginConsultarNfse(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginConsultarNfse(ByVal inputXML As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaCariocaProducaoAssinc.ConsultarNfseRequest = New NotaCariocaProducaoAssinc.ConsultarNfseRequest()
            inValue.inputXML = inputXML
            Return CType(Me,NotaCariocaProducaoAssinc.NfseSoap).BeginConsultarNfse(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_EndConsultarNfse(ByVal result As System.IAsyncResult) As NotaCariocaProducaoAssinc.ConsultarNfseResponse Implements NotaCariocaProducaoAssinc.NfseSoap.EndConsultarNfse
            Return MyBase.Channel.EndConsultarNfse(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndConsultarNfse(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaCariocaProducaoAssinc.ConsultarNfseResponse = CType(Me,NotaCariocaProducaoAssinc.NfseSoap).EndConsultarNfse(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginConsultarNfse(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inputXML As String = CType(inValues(0),String)
            Return Me.BeginConsultarNfse(inputXML, callback, asyncState)
        End Function
        
        Private Function OnEndConsultarNfse(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndConsultarNfse(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnConsultarNfseCompleted(ByVal state As Object)
            If (Not (Me.ConsultarNfseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ConsultarNfseCompleted(Me, New ConsultarNfseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ConsultarNfseAsync(ByVal inputXML As String)
            Me.ConsultarNfseAsync(inputXML, Nothing)
        End Sub
        
        Public Overloads Sub ConsultarNfseAsync(ByVal inputXML As String, ByVal userState As Object)
            If (Me.onBeginConsultarNfseDelegate Is Nothing) Then
                Me.onBeginConsultarNfseDelegate = AddressOf Me.OnBeginConsultarNfse
            End If
            If (Me.onEndConsultarNfseDelegate Is Nothing) Then
                Me.onEndConsultarNfseDelegate = AddressOf Me.OnEndConsultarNfse
            End If
            If (Me.onConsultarNfseCompletedDelegate Is Nothing) Then
                Me.onConsultarNfseCompletedDelegate = AddressOf Me.OnConsultarNfseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginConsultarNfseDelegate, New Object() {inputXML}, Me.onEndConsultarNfseDelegate, Me.onConsultarNfseCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_ConsultarNfsePorRps(ByVal request As NotaCariocaProducaoAssinc.ConsultarNfsePorRpsRequest) As NotaCariocaProducaoAssinc.ConsultarNfsePorRpsResponse Implements NotaCariocaProducaoAssinc.NfseSoap.ConsultarNfsePorRps
            Return MyBase.Channel.ConsultarNfsePorRps(request)
        End Function
        
        Public Function ConsultarNfsePorRps(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaProducaoAssinc.ConsultarNfsePorRpsRequest = New NotaCariocaProducaoAssinc.ConsultarNfsePorRpsRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaProducaoAssinc.ConsultarNfsePorRpsResponse = CType(Me,NotaCariocaProducaoAssinc.NfseSoap).ConsultarNfsePorRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_BeginConsultarNfsePorRps(ByVal request As NotaCariocaProducaoAssinc.ConsultarNfsePorRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaCariocaProducaoAssinc.NfseSoap.BeginConsultarNfsePorRps
            Return MyBase.Channel.BeginConsultarNfsePorRps(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginConsultarNfsePorRps(ByVal inputXML As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaCariocaProducaoAssinc.ConsultarNfsePorRpsRequest = New NotaCariocaProducaoAssinc.ConsultarNfsePorRpsRequest()
            inValue.inputXML = inputXML
            Return CType(Me,NotaCariocaProducaoAssinc.NfseSoap).BeginConsultarNfsePorRps(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_EndConsultarNfsePorRps(ByVal result As System.IAsyncResult) As NotaCariocaProducaoAssinc.ConsultarNfsePorRpsResponse Implements NotaCariocaProducaoAssinc.NfseSoap.EndConsultarNfsePorRps
            Return MyBase.Channel.EndConsultarNfsePorRps(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndConsultarNfsePorRps(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaCariocaProducaoAssinc.ConsultarNfsePorRpsResponse = CType(Me,NotaCariocaProducaoAssinc.NfseSoap).EndConsultarNfsePorRps(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginConsultarNfsePorRps(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inputXML As String = CType(inValues(0),String)
            Return Me.BeginConsultarNfsePorRps(inputXML, callback, asyncState)
        End Function
        
        Private Function OnEndConsultarNfsePorRps(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndConsultarNfsePorRps(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnConsultarNfsePorRpsCompleted(ByVal state As Object)
            If (Not (Me.ConsultarNfsePorRpsCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ConsultarNfsePorRpsCompleted(Me, New ConsultarNfsePorRpsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ConsultarNfsePorRpsAsync(ByVal inputXML As String)
            Me.ConsultarNfsePorRpsAsync(inputXML, Nothing)
        End Sub
        
        Public Overloads Sub ConsultarNfsePorRpsAsync(ByVal inputXML As String, ByVal userState As Object)
            If (Me.onBeginConsultarNfsePorRpsDelegate Is Nothing) Then
                Me.onBeginConsultarNfsePorRpsDelegate = AddressOf Me.OnBeginConsultarNfsePorRps
            End If
            If (Me.onEndConsultarNfsePorRpsDelegate Is Nothing) Then
                Me.onEndConsultarNfsePorRpsDelegate = AddressOf Me.OnEndConsultarNfsePorRps
            End If
            If (Me.onConsultarNfsePorRpsCompletedDelegate Is Nothing) Then
                Me.onConsultarNfsePorRpsCompletedDelegate = AddressOf Me.OnConsultarNfsePorRpsCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginConsultarNfsePorRpsDelegate, New Object() {inputXML}, Me.onEndConsultarNfsePorRpsDelegate, Me.onConsultarNfsePorRpsCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_ConsultarLoteRps(ByVal request As NotaCariocaProducaoAssinc.ConsultarLoteRpsRequest) As NotaCariocaProducaoAssinc.ConsultarLoteRpsResponse Implements NotaCariocaProducaoAssinc.NfseSoap.ConsultarLoteRps
            Return MyBase.Channel.ConsultarLoteRps(request)
        End Function
        
        Public Function ConsultarLoteRps(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaProducaoAssinc.ConsultarLoteRpsRequest = New NotaCariocaProducaoAssinc.ConsultarLoteRpsRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaProducaoAssinc.ConsultarLoteRpsResponse = CType(Me,NotaCariocaProducaoAssinc.NfseSoap).ConsultarLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_BeginConsultarLoteRps(ByVal request As NotaCariocaProducaoAssinc.ConsultarLoteRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaCariocaProducaoAssinc.NfseSoap.BeginConsultarLoteRps
            Return MyBase.Channel.BeginConsultarLoteRps(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginConsultarLoteRps(ByVal inputXML As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaCariocaProducaoAssinc.ConsultarLoteRpsRequest = New NotaCariocaProducaoAssinc.ConsultarLoteRpsRequest()
            inValue.inputXML = inputXML
            Return CType(Me,NotaCariocaProducaoAssinc.NfseSoap).BeginConsultarLoteRps(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_EndConsultarLoteRps(ByVal result As System.IAsyncResult) As NotaCariocaProducaoAssinc.ConsultarLoteRpsResponse Implements NotaCariocaProducaoAssinc.NfseSoap.EndConsultarLoteRps
            Return MyBase.Channel.EndConsultarLoteRps(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndConsultarLoteRps(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaCariocaProducaoAssinc.ConsultarLoteRpsResponse = CType(Me,NotaCariocaProducaoAssinc.NfseSoap).EndConsultarLoteRps(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginConsultarLoteRps(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inputXML As String = CType(inValues(0),String)
            Return Me.BeginConsultarLoteRps(inputXML, callback, asyncState)
        End Function
        
        Private Function OnEndConsultarLoteRps(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndConsultarLoteRps(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnConsultarLoteRpsCompleted(ByVal state As Object)
            If (Not (Me.ConsultarLoteRpsCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ConsultarLoteRpsCompleted(Me, New ConsultarLoteRpsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ConsultarLoteRpsAsync(ByVal inputXML As String)
            Me.ConsultarLoteRpsAsync(inputXML, Nothing)
        End Sub
        
        Public Overloads Sub ConsultarLoteRpsAsync(ByVal inputXML As String, ByVal userState As Object)
            If (Me.onBeginConsultarLoteRpsDelegate Is Nothing) Then
                Me.onBeginConsultarLoteRpsDelegate = AddressOf Me.OnBeginConsultarLoteRps
            End If
            If (Me.onEndConsultarLoteRpsDelegate Is Nothing) Then
                Me.onEndConsultarLoteRpsDelegate = AddressOf Me.OnEndConsultarLoteRps
            End If
            If (Me.onConsultarLoteRpsCompletedDelegate Is Nothing) Then
                Me.onConsultarLoteRpsCompletedDelegate = AddressOf Me.OnConsultarLoteRpsCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginConsultarLoteRpsDelegate, New Object() {inputXML}, Me.onEndConsultarLoteRpsDelegate, Me.onConsultarLoteRpsCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_ConsultarSituacaoLoteRps(ByVal request As NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsRequest) As NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsResponse Implements NotaCariocaProducaoAssinc.NfseSoap.ConsultarSituacaoLoteRps
            Return MyBase.Channel.ConsultarSituacaoLoteRps(request)
        End Function
        
        Public Function ConsultarSituacaoLoteRps(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsRequest = New NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsResponse = CType(Me,NotaCariocaProducaoAssinc.NfseSoap).ConsultarSituacaoLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_BeginConsultarSituacaoLoteRps(ByVal request As NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaCariocaProducaoAssinc.NfseSoap.BeginConsultarSituacaoLoteRps
            Return MyBase.Channel.BeginConsultarSituacaoLoteRps(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginConsultarSituacaoLoteRps(ByVal inputXML As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsRequest = New NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsRequest()
            inValue.inputXML = inputXML
            Return CType(Me,NotaCariocaProducaoAssinc.NfseSoap).BeginConsultarSituacaoLoteRps(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_EndConsultarSituacaoLoteRps(ByVal result As System.IAsyncResult) As NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsResponse Implements NotaCariocaProducaoAssinc.NfseSoap.EndConsultarSituacaoLoteRps
            Return MyBase.Channel.EndConsultarSituacaoLoteRps(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndConsultarSituacaoLoteRps(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaCariocaProducaoAssinc.ConsultarSituacaoLoteRpsResponse = CType(Me,NotaCariocaProducaoAssinc.NfseSoap).EndConsultarSituacaoLoteRps(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginConsultarSituacaoLoteRps(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inputXML As String = CType(inValues(0),String)
            Return Me.BeginConsultarSituacaoLoteRps(inputXML, callback, asyncState)
        End Function
        
        Private Function OnEndConsultarSituacaoLoteRps(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndConsultarSituacaoLoteRps(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnConsultarSituacaoLoteRpsCompleted(ByVal state As Object)
            If (Not (Me.ConsultarSituacaoLoteRpsCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ConsultarSituacaoLoteRpsCompleted(Me, New ConsultarSituacaoLoteRpsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ConsultarSituacaoLoteRpsAsync(ByVal inputXML As String)
            Me.ConsultarSituacaoLoteRpsAsync(inputXML, Nothing)
        End Sub
        
        Public Overloads Sub ConsultarSituacaoLoteRpsAsync(ByVal inputXML As String, ByVal userState As Object)
            If (Me.onBeginConsultarSituacaoLoteRpsDelegate Is Nothing) Then
                Me.onBeginConsultarSituacaoLoteRpsDelegate = AddressOf Me.OnBeginConsultarSituacaoLoteRps
            End If
            If (Me.onEndConsultarSituacaoLoteRpsDelegate Is Nothing) Then
                Me.onEndConsultarSituacaoLoteRpsDelegate = AddressOf Me.OnEndConsultarSituacaoLoteRps
            End If
            If (Me.onConsultarSituacaoLoteRpsCompletedDelegate Is Nothing) Then
                Me.onConsultarSituacaoLoteRpsCompletedDelegate = AddressOf Me.OnConsultarSituacaoLoteRpsCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginConsultarSituacaoLoteRpsDelegate, New Object() {inputXML}, Me.onEndConsultarSituacaoLoteRpsDelegate, Me.onConsultarSituacaoLoteRpsCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_RecepcionarLoteRps(ByVal request As NotaCariocaProducaoAssinc.RecepcionarLoteRpsRequest) As NotaCariocaProducaoAssinc.RecepcionarLoteRpsResponse Implements NotaCariocaProducaoAssinc.NfseSoap.RecepcionarLoteRps
            Return MyBase.Channel.RecepcionarLoteRps(request)
        End Function
        
        Public Function RecepcionarLoteRps(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaProducaoAssinc.RecepcionarLoteRpsRequest = New NotaCariocaProducaoAssinc.RecepcionarLoteRpsRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaProducaoAssinc.RecepcionarLoteRpsResponse = CType(Me,NotaCariocaProducaoAssinc.NfseSoap).RecepcionarLoteRps(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_BeginRecepcionarLoteRps(ByVal request As NotaCariocaProducaoAssinc.RecepcionarLoteRpsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaCariocaProducaoAssinc.NfseSoap.BeginRecepcionarLoteRps
            Return MyBase.Channel.BeginRecepcionarLoteRps(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginRecepcionarLoteRps(ByVal inputXML As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaCariocaProducaoAssinc.RecepcionarLoteRpsRequest = New NotaCariocaProducaoAssinc.RecepcionarLoteRpsRequest()
            inValue.inputXML = inputXML
            Return CType(Me,NotaCariocaProducaoAssinc.NfseSoap).BeginRecepcionarLoteRps(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_EndRecepcionarLoteRps(ByVal result As System.IAsyncResult) As NotaCariocaProducaoAssinc.RecepcionarLoteRpsResponse Implements NotaCariocaProducaoAssinc.NfseSoap.EndRecepcionarLoteRps
            Return MyBase.Channel.EndRecepcionarLoteRps(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndRecepcionarLoteRps(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaCariocaProducaoAssinc.RecepcionarLoteRpsResponse = CType(Me,NotaCariocaProducaoAssinc.NfseSoap).EndRecepcionarLoteRps(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginRecepcionarLoteRps(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inputXML As String = CType(inValues(0),String)
            Return Me.BeginRecepcionarLoteRps(inputXML, callback, asyncState)
        End Function
        
        Private Function OnEndRecepcionarLoteRps(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndRecepcionarLoteRps(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnRecepcionarLoteRpsCompleted(ByVal state As Object)
            If (Not (Me.RecepcionarLoteRpsCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent RecepcionarLoteRpsCompleted(Me, New RecepcionarLoteRpsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub RecepcionarLoteRpsAsync(ByVal inputXML As String)
            Me.RecepcionarLoteRpsAsync(inputXML, Nothing)
        End Sub
        
        Public Overloads Sub RecepcionarLoteRpsAsync(ByVal inputXML As String, ByVal userState As Object)
            If (Me.onBeginRecepcionarLoteRpsDelegate Is Nothing) Then
                Me.onBeginRecepcionarLoteRpsDelegate = AddressOf Me.OnBeginRecepcionarLoteRps
            End If
            If (Me.onEndRecepcionarLoteRpsDelegate Is Nothing) Then
                Me.onEndRecepcionarLoteRpsDelegate = AddressOf Me.OnEndRecepcionarLoteRps
            End If
            If (Me.onRecepcionarLoteRpsCompletedDelegate Is Nothing) Then
                Me.onRecepcionarLoteRpsCompletedDelegate = AddressOf Me.OnRecepcionarLoteRpsCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginRecepcionarLoteRpsDelegate, New Object() {inputXML}, Me.onEndRecepcionarLoteRpsDelegate, Me.onRecepcionarLoteRpsCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_CancelarNfse(ByVal request As NotaCariocaProducaoAssinc.CancelarNfseRequest) As NotaCariocaProducaoAssinc.CancelarNfseResponse Implements NotaCariocaProducaoAssinc.NfseSoap.CancelarNfse
            Return MyBase.Channel.CancelarNfse(request)
        End Function
        
        Public Function CancelarNfse(ByVal inputXML As String) As String
            Dim inValue As NotaCariocaProducaoAssinc.CancelarNfseRequest = New NotaCariocaProducaoAssinc.CancelarNfseRequest()
            inValue.inputXML = inputXML
            Dim retVal As NotaCariocaProducaoAssinc.CancelarNfseResponse = CType(Me,NotaCariocaProducaoAssinc.NfseSoap).CancelarNfse(inValue)
            Return retVal.outputXML
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_BeginCancelarNfse(ByVal request As NotaCariocaProducaoAssinc.CancelarNfseRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements NotaCariocaProducaoAssinc.NfseSoap.BeginCancelarNfse
            Return MyBase.Channel.BeginCancelarNfse(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginCancelarNfse(ByVal inputXML As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As NotaCariocaProducaoAssinc.CancelarNfseRequest = New NotaCariocaProducaoAssinc.CancelarNfseRequest()
            inValue.inputXML = inputXML
            Return CType(Me,NotaCariocaProducaoAssinc.NfseSoap).BeginCancelarNfse(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NotaCariocaProducaoAssinc_NfseSoap_EndCancelarNfse(ByVal result As System.IAsyncResult) As NotaCariocaProducaoAssinc.CancelarNfseResponse Implements NotaCariocaProducaoAssinc.NfseSoap.EndCancelarNfse
            Return MyBase.Channel.EndCancelarNfse(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndCancelarNfse(ByVal result As System.IAsyncResult) As String
            Dim retVal As NotaCariocaProducaoAssinc.CancelarNfseResponse = CType(Me,NotaCariocaProducaoAssinc.NfseSoap).EndCancelarNfse(result)
            Return retVal.outputXML
        End Function
        
        Private Function OnBeginCancelarNfse(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inputXML As String = CType(inValues(0),String)
            Return Me.BeginCancelarNfse(inputXML, callback, asyncState)
        End Function
        
        Private Function OnEndCancelarNfse(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndCancelarNfse(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnCancelarNfseCompleted(ByVal state As Object)
            If (Not (Me.CancelarNfseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CancelarNfseCompleted(Me, New CancelarNfseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CancelarNfseAsync(ByVal inputXML As String)
            Me.CancelarNfseAsync(inputXML, Nothing)
        End Sub
        
        Public Overloads Sub CancelarNfseAsync(ByVal inputXML As String, ByVal userState As Object)
            If (Me.onBeginCancelarNfseDelegate Is Nothing) Then
                Me.onBeginCancelarNfseDelegate = AddressOf Me.OnBeginCancelarNfse
            End If
            If (Me.onEndCancelarNfseDelegate Is Nothing) Then
                Me.onEndCancelarNfseDelegate = AddressOf Me.OnEndCancelarNfse
            End If
            If (Me.onCancelarNfseCompletedDelegate Is Nothing) Then
                Me.onCancelarNfseCompletedDelegate = AddressOf Me.OnCancelarNfseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCancelarNfseDelegate, New Object() {inputXML}, Me.onEndCancelarNfseDelegate, Me.onCancelarNfseCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
